### ISSUE TITLE
02 - 3X & Butter type pages (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1003]
## Description
In the reference image below, you are looking at the brand new 3X/Butter type page for the popcorndao.finance site. 
Website architecture explainer video (Please request with me for access if this is your first time watching a Loom video): https://www.loom.com/share/b67f67e79261474c8075bd2466aaf6af

## Specific Acceptance Criteria
- Reskin all components, on-hover tooltips and website layout for 3X & Butter (Desktop & Mobile)
- 12 column grids system (Please study the Figma file)
- use nextJS images / JSON animation (faster load)
- Fetch data for all relevant data shown
- Button hover state for key CTA "Mint", "Claim", "Claim & Stake"

## Resources
(Please study the Figma file carefully.)
https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=1614%3A37779

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
Button States
![Screen Shot 2022-07-28 at 3.56.48 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b4b70cd3-3c17-4697-89eb-8521b272c9ff)
On-hover tooltip example
![Screen Shot 2022-07-28 at 5.18.57 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/28916089-4f89-41c9-9819-e4ab6fb300c8)
State 1: The user has not minted any 3X or Butter
![New user landing.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2a731de5-b70c-427f-9a03-66baaf58aa22)
![New user landing-1.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/567436de-ec61-4d9c-a897-26687c3a60a9)
State 2: The user has multiple batches under the Your Batches table
![Redeem.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/4f216e8d-1c02-43a5-8611-ddead3da8d85)
![Mint-2.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/4e04d662-1ae4-4dc7-ab4e-3eedfe69208f)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/1003?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @K-G-J @RedVeil

**Comment by RedVeil** [comment]
Left Comments

**Comment by RedVeil** [comment]
This is the PR btw. https://github.com/popcorndao/sweet-caramel/pull/1078

**Comment by RedVeil** [comment]
@anthonymartin For future reference. We need to redesign the token input so that it works on mobile. ![grafik.png](https://images.zenhubusercontent.com/5d23b426292a4707ce2b61d3/9f1df046-4054-474b-8236-a1b885b1c81e)

**Comment by anthonymartin** [comment]
@RedVeil @FanFanDAO i was thinking about this. can we remove the max button and use the user's token balance as a link to set the input amount to their balance?

**Comment by FanFanDAO** [comment]
@RedVeil @FanFanDAO The Max button functionality is a widely adopted UX within Defi. I think people register with it, and we should not remove it.
If we look at the improved form in our design system, based on our previous discussion, we are not showing the "token name" within the input field. @RedVeil  can you double-check?
Figma link (Page: Form): https://www.figma.com/file/5bmpYjaYkpoefISS9afbHc/Design-System?node-id=6502%3A4690
![Screen Shot 2022-08-11 at 2.02.56 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/85f14835-1d17-42ec-9220-d607633f484e)

**Comment by FanFanDAO** [comment]
@Ajiva-D feedback
![Screen Shot 2022-08-17 at 5.50.40 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/63c9a4f1-7176-441f-b93f-e1d668f38c0b)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback:
https://www.loom.com/share/d55d23bea0cf492d9b5dcac9afc1b7ac
![Screen-Shot-2022-08-18-at-12.33.46-PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/69e05891-37a8-41f6-95f1-2fc186780194)
![Screen-Shot-2022-08-18-at-12.32.59-PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/432b9fdb-dadb-432f-9c5b-90f0a4404078)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback:
![Screen Shot 2022-08-18 at 1.39.58 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9545f6b3-7c78-4b42-9e9b-a6121428db75)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback: icon not-shown
![Screen Shot 2022-08-18 at 1.19.41 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1d365562-2f5c-4307-9d67-f25e5395aad0)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback: 2.5 rem is 40px. The font here should be 32px.
![Screen Shot 2022-08-18 at 6.11.51 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e7fd983d-ab9a-4462-8131-711462ea5476)
![Screen Shot 2022-08-18 at 5.36.07 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/94f27a54-40bb-40ff-a17b-14f0d7c35e02)
2
![Screen Shot 2022-08-18 at 5.36.13 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/89889270-7b3a-4f91-b367-5ec7d597ce40)

**Comment by FanFanDAO** [comment]
@Ajiva-D feedback:
![Screen Shot 2022-08-18 at 6.40.37 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e408b2b2-36d7-47e7-a6d0-6143f64b039d)
