### ISSUE TITLE
03 - Staking Landing Pages (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1004]
## Description
In the reference image below, you are looking at the brand new Staking landing type page for the popcorndao.finance site. 
Website architecture explainer video (Please request with me for access if this is your first time watching a Loom video): https://www.loom.com/share/3421c035f3434be58be26fff36a2f71c

## Specific Acceptance Criteria
- Reskin all components, on-hover tooltips and website layout for Staking (Desktop & Mobile)
- 12 column grids system (Please study the Figma file)
- use nextJS images / JSON animation (faster load)
- Fetch data for all relevant data shown
- Button hover states for "View"
- Use the ready-made top nav & footer from the main landing page 

## Resources
(Please study the Figma file carefully.)
https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=1614%3A37779

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
Button States
![Screen Shot 2022-07-28 at 3.56.48 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b4b70cd3-3c17-4697-89eb-8521b272c9ff)
On-hover tooltip example
![Screen Shot 2022-07-28 at 5.18.57 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/28916089-4f89-41c9-9819-e4ab6fb300c8)
State 1: Staking Landing
![staking (1).jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/74bfaa93-6d40-4983-b838-649b272b1e1e)
![staking (1).jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/17587a7f-b437-418f-a013-3d7472d5cec0)
State 2: Alert card for migration and any applicable notification
![Migration.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/85694451-451a-4fe6-be94-89353fcac30f)
![Migration.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c0461882-29d2-4a94-b79b-9fa1b02b8403)

**Comment by Ajiva-D** [comment]
pr: https://github.com/popcorndao/sweet-caramel/pull/1078

**Comment by Ajiva-D** [comment]
pr: https://github.com/popcorndao/sweet-caramel/pull/1079

**Comment by FanFanDAO** [comment]
@Ajiva-D @anthonymartin 
Anthony would like to bring back the animation that magnifies on-hover and have the whole panel clickable. Let's try this, but this is the last priority. Not urgent.
