### ISSUE TITLE
04 - Staking Detail Pages (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1005]
## Description
In the reference image below, you are looking at the brand new Staking detail type page for the popcorndao.finance site. 
Website architecture explainer video (Please request with me for access if this is your first time watching a Loom video): https://www.loom.com/share/c66975d50ea94ce8a2fac51ea8cbea46

## Specific Acceptance Criteria
- Reskin all components, on-hover tooltips and website layout for Staking Detail Page (Desktop & Mobile)
- 12 column grids system (Please study the Figma file)
- use nextJS images / JSON animation (faster load)
- Fetch data for all relevant data shown
- Button hover states for "Approve to Begin" "MAX" and any relevant buttons to the form
- Use the ready-made top nav & footer from the main landing page 

## Resources
(Please study the Figma file carefully.)
https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=1614%3A37779

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
Button States
![Screen Shot 2022-07-28 at 3.56.48 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b4b70cd3-3c17-4697-89eb-8521b272c9ff)
On-hover tooltip example
![Screen Shot 2022-07-28 at 5.18.57 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/28916089-4f89-41c9-9819-e4ab6fb300c8)
Staking Detail Page
![staking detail (2).jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ca4086e0-993c-4326-8029-77e3adbe8084)
![New user landing.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b646b842-971c-47e0-9ea7-a7a3cb68482a)

**Comment by Ajiva-D** [comment]
pr: https://github.com/popcorndao/sweet-caramel/pull/1093
deploy link: https://sweet-caramel-git-new-staking-detail-page-popcorn-dao.vercel.app/ethereum/staking/pop

**Comment by FanFanDAO** [comment]
@Ajiva-D Fixes @RedVeil @anthonymartin 
We are launching next week. Can one of you work on fixing this asap?
All data in mobile value here should be 20px:
![Screen Shot 2022-08-12 at 8.38.13 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a17870a9-77d7-4418-b23b-3688fbc3feae)
The green dot is not positioned appropriately. The frame should be in color: #645F4B
![Screen Shot 2022-08-12 at 8.38.01 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d2b44210-1383-43e7-9aeb-59bac13035b1)

Otherwise, its good to me.

**Comment by Ajiva-D** [comment]
@FanFanDAO comments here have been addressed

**Comment by Ajiva-D** [comment]
@FanFanDAO comments here have been addressed

**Comment by FanFanDAO** [comment]
@Ajiva-D Contract titles in mobile should be 24px.
Reference from our Figma:
![Screen Shot 2022-08-15 at 7.38.32 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2f53bf3e-6401-4284-9027-f60924f0bdcd)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback
![Screen Shot 2022-08-16 at 3.31.08 PM.psd](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2eb42740-94f8-4dc9-a8f0-a6d0854f32bf)
![Screen Shot 2022-08-16 at 3.31.32 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/50fd4988-99f4-43ea-8a4b-6f96b86d2135)

**Comment by FanFanDAO** [comment]
@Ajiva-D To #ffe650
![Screen Shot 2022-08-17 at 5.52.07 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b32a7d4f-9866-4ae1-819b-abdfef7f6f58)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback:
https://www.loom.com/share/d55d23bea0cf492d9b5dcac9afc1b7ac
![Screen Shot 2022-08-18 at 12.30.34 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/cfcd0ee7-db97-4284-b18f-f4a55fd52df2)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback:
![Screen Shot 2022-08-18 at 1.39.58 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8c38c738-90a6-4d24-bb8e-b370c4dd491f)
