### ISSUE TITLE
06 - Sweet Vaults Pages (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1007]
## Description
In the reference image below, you are looking at the brand new Sweet Vault pages for the popcorndao.finance site. 
Website architecture explainer video (Please request with me for access if this is your first time watching a Loom video): https://www.loom.com/share/b3c795ea87ea4081a397f6503eed44f2

## Specific Acceptance Criteria
- Reskin all components and website layout for Sweet Vaults Pages  (Desktop & Mobile)
- 12 column grids system (Please study the Figma file)
- use nextJS images / JSON animation (faster load)
- Fetch data for all relevant data shown
- Button hover states for "Deposit & Stake," "Approve," "MAX," Seach icon, "Get Token," and pagination for the Vesting Records
- Use the ready-made top nav & footer from the main landing page 

## Resources
(Please study the Figma file carefully.)
https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=1614%3A37779

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
Button States
![Screen Shot 2022-07-28 at 3.56.48 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b4b70cd3-3c17-4697-89eb-8521b272c9ff)
Sweet Vaults Page
![Sweet vaults (1).jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9457574b-dbe8-4012-aaa5-2e17a734a011)
![Sweet vaults.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/47520ec8-5df3-46f4-9dca-9dfa90e62809)

**Comment by RedVeil** [comment]
@Ajiva-D Looking very good just a few comments:

**Comment by RedVeil** [comment]
I think we should make the input part larger so that we have a proper grid here:
![grafik.png](https://images.zenhubusercontent.com/5d23b426292a4707ce2b61d3/45a7233b-7da4-471c-bc65-204e01987b9f)

Also the text box should have one fixed height. If a text is to long we can either add a scrollbar or simply shorten them.
![grafik.png](https://images.zenhubusercontent.com/5d23b426292a4707ce2b61d3/3d045241-f7c8-4520-b67b-97dfd537f918)

**Comment by Ajiva-D** [comment]
@RedVeil the form is part of the overall form ticket, I don't think I should make changes there to avoid conflicts, I think it should be handled in the form updates ticket.

**Comment by Ajiva-D** [comment]
@RedVeil for the slider, there's the option to swipe from left to right and the other way around too. I'm not sure if clicking the card is the best experience, especially when we move to mobile. We could also make the dots bigger if necessary.

**Comment by RedVeil** [comment]
@Ajiva-D The form updates PR only updates the dropdown. I just want that the card with text + the "get token" card have together the same height as the card with all the inputs next to it. And making the card with the info text a fixed height should also not influence the form updates ticket. 

I didnt know about the slider. That works and i agree that we should increase the size of the dots slightly.

**Comment by FanFanDAO** [comment]
@Ajiva-D @RedVeil Please keep me posted on the PR for all UI reviews and assign me. I got your conversation through the email notification, and I saw a drop shadow for the form, as shown in the above images. We don't have drop shadows in this case.

**Comment by FanFanDAO** [comment]
@RedVeil @Ajiva-D Looks nice to meet you from our share screen review. Please check in with Anthony on the height auto-scaling, and then we are good with the frontend UI for this ticket. QA is separate scope.
