### ISSUE TITLE
capture all transactions from erc20 transfer events

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#1020]
**Description**
Currently, the emissions dashboard does not capture transfer events from erc20's. In order to get more accurate reporting - we should iterate through transfers for erc20 contracts (as denoted by some property in the configuration object), and for each transfer add the related transaction to the collection for analysis.

**Acceptance Criteria**
All POP token transfer event transactions should be added to the dashboard for reporting.

**Additional context**
https://app.zenhub.com/workspace/o/popcorndao/workspace/issues/868

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/1020?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @K-G-J @RedVeil

**Comment by Amirjab21** [comment]
The issue with this ticket is the fact that etherscans Account txlist API endpoint only captures certain transactions (and this is a very small subset of total transactions)

The way to do this is to use their logs API endpoint, capture all the logs, use this information to get all the transaction hashes, remove duplicates and then use the gas used and other tx data it provides to do so. I'm on it

**Comment by Amirjab21** [comment]
Just double checked - this actually seems to be working fine so can be closed.

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/workspace/pull/910
