### ISSUE TITLE
update historical data

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#1021]

**Comment by Amirjab21** [comment]
This requires database access - we need to pull in all the date estimates from patch's database onto our own.

**Comment by anthonymartin** [comment]
can you write a script for this?

**Comment by Amirjab21** [comment]
@anthonymartin I have written a script that resolves this issue but it takes way longer than 10 seconds so this may have to be run locally with on someones machine who has db access - the script is called backdate-patch-estimations.ts in the latest commit:
https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/1021
