### ISSUE TITLE
07 - Popover for Coming Soon (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1022]
## Description
In the reference image below, you are looking at the brand new popover for Coming Soon/Delay notification for the popcorndao.finance site. 
We simply need to reskin the UI for both desktop and mobile.

## Specific Acceptance Criteria
- Reskin all components and layout (Desktop & Mobile)
- Use the correct background color and opacity
- use nextJS images / JSON animation (faster load)

## Resources
(Please study the Figma file carefully.)
https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=1614%3A37779

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Coming Soon.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/47785013-c8c3-466d-97bc-33c90875c14a)
![Coming Soon_mobile.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e79e5f12-e21c-485a-96dd-c5b42a036f91)

**Comment by Ajiva-D** [comment]
All the popovers can be tested for here https://sweet-caramel-git-new-modal-designs-popcorn-dao.vercel.app/

**Comment by Ajiva-D** [comment]
![Screenshot 2022-08-15 at 16.32.20.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/26d927c5-634e-44a9-8ee6-c3d79cab8ee2)

**Comment by FanFanDAO** [comment]
@anthonymartin @RedVeil Looks good to me. We can merge this.

**Comment by FanFanDAO** [comment]
@Ajiva-D can you find out why this is not looking right?
![screen_shot_2022-09-15_at_10.50.52_pm.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/12b47600-0cc2-41f3-af7c-4f1ff71c4c4f)

**Comment by Ajiva-D** [comment]
I have reverted the change that was made during a merge @FanFanDAO 
 ![Screenshot 2022-09-16 at 12.28.25.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/5f39aeec-6e1f-4992-b69c-e4c09f7c7bc8)

**Comment by FanFanDAO** [comment]
@anthonymartin, I can't trigger this preview, and therefore David submitted a screenshot as proof, and the issue had been explained above. It looks good to me.
