### ISSUE TITLE
10 - Popover Term and conditions (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1025]
## Description
In the reference image below, you are looking at the brand new popover for Terms & Conditions for the popcorndao.finance site. 
We simply need to reskin the UI for both desktop and mobile.

## Specific Acceptance Criteria
- Reskin all components and layout (Desktop & Mobile)
- Use the correct background color and opacity
- use nextJS images / JSON animation (faster load)

## Resources
(Please study the Figma file carefully.)
https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=1614%3A37779

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Term and conditions.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2c8ba5f2-b262-46b9-8701-9921215899ba)
![Term and conditions_mobile.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e8722443-48cb-4488-9864-f3904bb604e8)

**Comment by Ajiva-D** [comment]
[Uploading... Screenshot 2022-08-15 at 17.28.06.png]

**Comment by Ajiva-D** [comment]
![Screenshot 2022-08-15 at 17.28.06.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/595d2770-67d3-4363-9d5d-743b34c360e3)

**Comment by FanFanDAO** [comment]
@anthonymartin @RedVeil Looks good to me. We can merge this.
