### ISSUE TITLE
11 - Popover Time to Restake (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1026]
## Description
In the reference image below, you are looking at the brand new popover for Time to restake d notification for the popcorndao.finance site. 
We simply need to reskin the UI for both desktop and mobile.

## Specific Acceptance Criteria
- Reskin all components and layout (Desktop & Mobile)
- Use the correct background color and opacity
- use nextJS images / JSON animation (faster load)

## Resources
(Please study the Figma file carefully.)
https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=1614%3A37779

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Time to Restake.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9769bac5-d63a-45fb-a9a8-87f44dd6970d)
![Time to Restake_mobile.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2e7f4b71-087b-476a-a6f3-9a55f04f7323)

**Comment by Ajiva-D** [comment]
![Screenshot 2022-08-15 at 17.21.50.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/79787b5d-4e64-46aa-9d21-ddcc872bb311)

**Comment by FanFanDAO** [comment]
@anthonymartin @RedVeil Looks good to me. We can merge this.
