### ISSUE TITLE
Restake Alert is a bit to aggressive

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1034]
The Restake alert pops up on every page change and sometimes even multiple times on the same page.
This is quite annyoing.
Im not sure if we should hide the modal completly if someone presses dismiss though.
Maybe we should attach a timestamp to the dismiss and not bother the user until a certain time after the last dismiss has past?

**Comment by anthonymartin** [comment]
* should only show the modal once per day if the user dismisses it

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/1104
