### ISSUE TITLE
Fix Dependabot Alerts

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1038]

**Comment by RedVeil** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1036

This should address all critical,high and moderate priority issues

**Comment by anthonymartin** [comment]
I believe this change was not accepted by dependabot

**Comment by RedVeil** [comment]
Second PR https://github.com/popcorndao/sweet-caramel/pull/1087
