### ISSUE TITLE
15 - Form updates (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1095]
## Description
We have optimized our forms to address the long token names and user balances issues. Basically, we are removing the use of the token name in our form and simply showcasing user balance with a wallet icon next to it. 
If there are any other tokens that can be selected the dropdown arrow next to the inputToken will open a pop-over. In there we show the available token. In here the user can also learn about the full token name. We have a default token list that shows the most common token a user might want to use. These should be filtered by page to make sure we only show applicable ones. (We wouldnt want to show eth or wbtc for example in the butter pages).

## Specific Acceptance Criteria
**Popover**
- An on-click popover design for when someone clicks the dropdown token icon
- Filter defaultTokenList to only include applicable tokens for the quick selection  
- Quick buttons for: usdc, dai, usdt, eth, wbtc

**Form**
- Make sure we update the arrow down SVG art to one-directional ( Check reference images below)
- Address all layouts for both desktop & mobile
- The token balance underneath uses `formatAndRoundBigNumber`
- Address form: Mint & Redeem (3X & BTR)
- Address form: Stake & Unstake (Staking)
- Address form: Deposit & Withdraw (Sweet Vaults)
- Address form: Redeem (xPOP)

## Resources
Design System > Form

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and normally work across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-08-29 at 3.57.44 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/274cee5a-de00-4647-918b-f78a8e11a3ea)
![Screen Shot 2022-08-29 at 3.57.53 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f462c336-6a78-4b84-bc55-bde1383bfdb7)
![Screen Shot 2022-08-29 at 4.10.01 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/efe6f8b2-5220-4c9a-a50c-c2f0eae157e4)
![Screen Shot 2022-08-29 at 3.58.05 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3b04a6be-e2f4-4d77-b3e3-d7c02eccc9ba)
![Screen Shot 2022-08-29 at 4.42.58 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/aeaf6e54-7f2c-47d4-827c-49545ce9d45b)
![Screen Shot 2022-08-29 at 3.58.13 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/aef66849-ed72-490e-b6f1-2ee1b2890f21)
![Screen Shot 2022-08-29 at 4.09.55 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d69d6514-1c35-4de8-a810-d76a4e46c5a7)
![Screen Shot 2022-08-24 at 5.09.16 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8ac7078d-1be9-4b92-a0c4-d11d394f393d)

**Comment by FanFanDAO** [comment]
Desktop: 26 max characters, 13:13, prioritize name and truncate number when reaching the max length

Mobile: 16 max characters, 8:8, prioritize name and truncate number when reaching the max length

**Comment by RedVeil** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Re-brand-62fa2ce6c8a7c5fb06d1e054/issues/popcorndao/sweet-caramel/1095?planning-poker) with Zenhub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @FanFanDAO

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/1188

**Comment by FanFanDAO** [comment]
@RedVeil @oluwatunmiisheii Feedback:
- “Search a token” should say  “Select a token”
- “Search a name” should say “Search”
- additionally, and most importantly, the scrolling options menu does not react after tapping a selection"

We need this done asap.

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO here is the preview link
https://new.popcorndao.finance/ethereum/set/3x

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Discussion from Sprint Planning:

## Specific Acceptance Criteria
- should become scrollable select and not a wheel menu for both desktop and mobile
- dev should sync with Arne cause of refactor

**Comment by FanFanDAO** [comment]
@Adenuga Oluwatunmise

New issues found: https://www.loom.com/share/b1cbe7b57b1b40fc9c54ec96691da628
Convension of a popover: https://www.loom.com/share/f938dce959d5448aa28dd7a2e9548941
Please address this as soon as possible.
Popover is too tall and the "x" button is still cut off. This happens at a 1440px laptop and viewing at 100%. If you reference our Figma file designed for a 1440p screen it has enough space to contain the popover.
Search bar: when I type D, I get DAI and USDT (If USDC is selected). This is wrong. Only DAI should be shown (Desktop & Mobile)
Search bar: when I type U, I get USDT only if USDC is selected. This is wrong. USDT and USDC should be shown with USDC being selected. (Desktop & Mobile)
The scroll selection menu container should have a fixed height and not change when there are fewer tokens. You have done right in mobile. Please address on desktop.

**Comment by FanFanDAO** [comment]
@anthonymartin This is good to know.
QA video on this popover: https://www.loom.com/share/05ddb48a7e7d494ba3386a5b8e0ca980
