### ISSUE TITLE
[chore] update arrakis simulations

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#1106]
**Description**
It turns out that about 200k of liquidity is being unused by arrakis after the last executive rebalance. For this task we should update the simulations to include the following properties in the csv export: `arrakis_usdc_balance_before`, `arrakis_usdc_balance_after`. Additionally, we should run a simulation w/ another executive rebalance with the current range `20,0.5` to see what happens to the liquidity and if necessary experimenting with more rebalances to see how the arrakis uses the liquidity.

**Acceptance Criteria**
- [x] update block number in fork to latest
- [x] add `arrakis_usdc_balance_before` to csv export (should take balance of USDC held by arrakis vault)
- [x] add `arrakis_usdc_balance_after` to csv export  (should take balance of USDC held by arrakis vault)
- [x] export csv with simulation using  the following ranges: 
`20,0.5`
`20,1`
`20,2`
`0.5,20`
`1,20`
`2,20`

**Additional context**
branch: `feature/arrakis-simulations`
affected files: `packages/hardhat/test/fork/uni-v3-simulation.test.ts`
running test: `yarn hardhat test test/fork/uni-v3-simulation.test.ts`

**Comment by arne-z** [comment]
https://drive.google.com/file/d/1D-LjXPfNh_7FA5-XYVzezv--yLt-LKnI/view?usp=sharing
CSV Found in drive

**Comment by arne-z** [comment]
A more complete CSV with all the rebalances and additional into on the status of the uni pool:
https://drive.google.com/file/d/1zKQ11E6roVt7faVm2TUXU2VQ3myT5pzp/view?usp=sharing

**Comment by anthonymartin** [comment]
this was implemented incorrectly as it was intended for the balances to be retrieved before and after the rebalance, not the swap. I've update this and fixed it.
