### ISSUE TITLE
Decouple Deploy script from demo data creation

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1117]
In order to make our deployment more flexible and easier to work with we should decouple the deployment of contracts from demo data creation and make more use of tags in order to specify which scripts really need to run.

This should allow us to use a command like `yarn hardhat deploy --tags staking,staking-demo,3x,3x-demo` to specify exactly which contracts and demo data is needed for the deployment.

- [x] Add tag to `01_AclRegistry`
- [x] Add tag to `02_ContractRegistry`
- [x] Remove POP_USDC_LP and XPOP deployment from 04_TestToken, rename 04_TestToken to 04_TestPop
- [x] Add a new file to mint pop (Cut the `mintPOP` function from 04_TestToken) and add a specific tag for it. This should also contain a dependency to the tag `test-tokens` 
- [x] Move `createDemoData` from `07_Staking` into its own file with a specific tag and a dependency of `staking`
- [x] Move `createDemoData` from `08_ButterBatch` into its own file with a specific tag and a dependency of `butter`
- [x] Move `createDemoData` from `09_ThreeX` into its own file with a specific tag and a dependency of `3x`
- [x] Move the `mintPop` calls from `09_xPopRedemption` into its own file with a specific tag and a dependency of `xpop-redemption`
- [x] Add an env variable to .env.example named `DEPLOYMENT_BLOCK_NUMBER` (Take this from `feature/sweet-pool-integration` including comment)
- [x] In `00_setup` use `DEPLOYMENT_BLOCK_NUMBER` if its defined in .env for blockNumber otherwise use `undefined` (Take this from `feature/sweet-pool-integration`)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/1117?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @K-G-J @RedVeil

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1154
