### ISSUE TITLE
18 - Popover for Network Inconsistency

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1120]
## Description
In the reference image below, you are looking at the brand new popover for Network Incosistency notification for the popcorndao.finance site. 
We simply need to reskin the UI for both desktop and mobile.

## Specific Acceptance Criteria
- Reskin all components and layout (Desktop & Mobile)
- Use the correct background color and opacity
- use nextJS images / JSON animation (faster load)

## Resources
(Please study the Figma file carefully.)
https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=1614%3A37779

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-08-17 at 12.09.59 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d2791afb-6830-4aed-a005-e45f928cf52a)

**Comment by Ajiva-D** [comment]
@FanFanDAO  ![Screenshot 2022-08-29 at 14.38.01.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/f127dba0-288d-44cc-86f7-633f6a5c1fd2)
