### ISSUE TITLE
Test Stargate USDT integration

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1132]
Make sure the yearn Stargate USDT vault works properly with Zapper.ts, ZeroXZapper.sol and Vault.sol. Todo so write a test for the Stargate USDT vault based on the hardhat/test/fork/vault/ZapperModule.test.ts.

It should test:
- [x] Depositing and Withdrawing USDT directly
- [x] Swapping from another stablecoin into USDT for deposit using Zapper.ts
- [x] Swapping into another stablecoin from USDT after withdrawal using Zapper.ts
- [x] Swapping from ETH into USDT for deposit using Zapper.ts
- [x] Swapping into ETH from USDT after withdrawal using Zapper.ts
- [ ] Frontend functions for interacting with the vault should work

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vaults-62f6d790f4a4fa0011c65c97/issues/popcorndao/sweet-caramel/1132?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @K-G-J

**Comment by arne-z** [comment]
@arne-z 
TODO: Cherry pick relevant changes out of the existing PR and make a new PR with only the relevant diffs.

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/1217
