### ISSUE TITLE
Test 3Crypto Integration

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1134]
Make sure the yearn 3Crypto vault works properly with Zapper.ts, ZeroXZapper.sol and Vault.sol. Todo so write a test for the 3Crypto vault based on the hardhat/test/fork/vault/ZapperModule.test.ts.

It should test:
- [x] Depositing and Withdrawing 3Crypto directly
- [x] Swapping from another token into 3Crypto for deposit using Zapper.ts
- [x] Swapping into another token from 3Crypto after withdrawal using Zapper.ts
- [x] Using an underlying of 3Crypto and zapping into 3Crypto for deposit using Zapper.ts
- [x] Zapping out into an underlying of 3Crypto after withdrawal using Zapper.ts

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/1168
