### ISSUE TITLE
19 - Adjust Slippage Expanded

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1137]
## To-do
The styling reference for Adjust Slippage is here. Please refer to the reference image.

## Resource 
Under form from within the Design system. 

## Reference Image
![Screen Shot 2022-08-22 at 11.25.51 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/fe81ae45-f9bf-4a1f-8cee-8682b047243b)

**Comment by FanFanDAO** [comment]
@RedVeil @Ajiva-D As discussed, we are doing the below. Is this done?
Desktop:
![Screen Shot 2022-09-02 at 12.53.06 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e34b8069-7318-48ae-b2b5-d29c3c18c883)S
Mobile:
![Screen Shot 2022-09-02 at 12.51.05 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/359bffe0-8cfa-4013-b69e-40c0e0bfcab0)

**Comment by Ajiva-D** [comment]
@FanFanDAO this has been done
