### ISSUE TITLE
Fee Escrow

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1139]
We need to create a central fee escrow contract which gets fees from various contracts in the system and stores a mapping of feeTokenAddress to burnerAddress. This mapping can be accessed in the burner contracts to see if the contract is eligible to receive feeToken from the fee escrow contract.

FeeEscrow should have:
- [x] A mapping in storage of feeTokenAddres to burnerAddress
- [x] It should add or remove burner addresses from these mappings.
- [x] a permissionless function, `transferFees(address token)` will send fees to the burner which is registered for that token address, and if one does not exist it will revert

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/1139?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @K-G-J @RedVeil

**Comment by K-G-J** [comment]
[link to the PR](https://github.com/popcorndao/sweet-caramel/pull/1258)
