### ISSUE TITLE
Simplify getNamedAccounts

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1150]
Updating contract addresses for hardhat is quite tedious. At this point we should automate this process.
`Hardhat-deploy` has a command which exports all deployed contracts per specified chain into a single json in the pattern:
`{
  "name": "localhost",
  "chainId": "1337",
  "contracts": {
    ContractName: {
      "address": string,
      "abi": abi
    }
}`
We can use this json and export the new addresses into our getNamedAccounts. 
! We dont want to overwrite any other addresses besides the addresses for the `hardhat` network!
For this getNamedAccounts should become a json. This also means that the functions in `getContractAddresses.ts` should be updated to handle a json instead of a ts object.

TODO: 
- [x] We should update the node command to `yarn hardhat node --network hardhat --export ./deployments.json && exportAddresses`
- [x] The `exportAddresses` command should loop over the json and take all the addresses in there and write them into `namedAccounts.json` for the hardhat network this should be a seperate file from the json file that hosts all permanent addresses for contracts on all the other networks
- [x] The script should first use all keys from the main `getNamedAccounts.json` and use the mainnet addresses. It should than overwrite all keys that were deployed with the actual deployed address on hardhat. (Since we always fork mainnet this should fill in all contracts that we didnt explicitly deployed but should reduce errors like in `stakingContractNames`)
- [x] On each new run of the script it should overwrite the existing `hardhatNamedAccounts.json`. (If someone runs a full deployment first and than a specific tagged deployment afterwards we dont want the frontend to pick up all the other old contract addresses that are no longer deployed from the first deployment.)
- [x] `getNamedAccounts.ts` should become a `namedAccounts.json` which holds exactly the same structure just in a json-format
- [ ] All functions in `getContractAddresses.ts` should work exactly the same as before but use `namedAccounts.json` as the basis instead of `getNamedAccounts.ts`

**Comment by RedVeil** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/1150?planning-poker) with Zenhub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall

**Comment by Amirjab21** [comment]
Questions:

Should it completely overwrite hardhatNamedAccounts.json or just upsert any contracts that were deployed on the deployment?

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1187/
