### ISSUE TITLE
04 - Ideas Page (Foundation Site) (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1157]
## Description
We are doing an MVP rebrand reskin process for our Foundation site. 
Here's the explainer for the design: https://www.loom.com/share/93ecffb7d7e6465bb44b96562ccd675d

## Specific Acceptance Criteria
- Use the hook explained in this article to fetch articles https://javascript.plainenglish.io/how-to-fetch-your-medium-articles-in-your-website-31b79df9377f
- Use the next SVG, and JS images whenever possible for faster load time
- Fetch data & articles accurately from the Medium API https://github.com/Medium/medium-api-docs
- The layout of the page (Desktop & Mobile)

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![desktop:ideas.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2b75ede5-fc30-48c2-9f2d-4e49abcf4b23)
![mobile:ideas.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2f45ada6-614f-47af-a63c-8856bcf6adff)

**Comment by arne-z** [comment]
https://github.com/Medium/medium-api-docs

**Comment by RedVeil** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Re-brand-62fa2ce6c8a7c5fb06d1e054/issues/popcorndao/sweet-caramel/1157?planning-poker) with Zenhub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Feedback: For articles, let's make them the same ratio on mobile, so images are not force-cropped into a square.
![Screen Shot 2022-09-13 at 4.16.11 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3a021d14-b002-4b48-b988-77e9ac6c9595)

**Comment by oluwatunmiisheii** [comment]
I am not sure i understand what you mean by same aspect ratio @FanFanDAO

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Another thing: please use this spacing. It is a bit loosely spaced from the preview link.
![Screen-Shot-2022-09-13-at-4.49.42-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e16b49ab-cbaa-4309-9116-d9ec17bc2556)

**Comment by oluwatunmiisheii** [comment]
Done @FanFanDAO

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO here is the preview link
https://popcorn-foundation-g5pvz8ak4-popcorn-dao.vercel.app/

**Comment by FanFanDAO** [comment]
Looks good on the preview. done.
