### ISSUE TITLE
05 - Grants Page (Foundation Site) (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1158]
## Description
We are doing an MVP rebrand reskin process for our Foundation site. 
Here's the explainer for the design: https://www.loom.com/share/93ecffb7d7e6465bb44b96562ccd675d

## Specific Acceptance Criteria
- Use the next SVG, and JS images whenever possible for faster load time
- Fetch data accurately for all links
- The layout of the page (Desktop & Mobile)

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![desktop:grants.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/df1de6af-c966-44a4-ad23-9bac8d04d163)
![mobile:grants v1.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e6ac200c-c512-462c-b854-a4364396d056)

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Can we size the heart art, so it looks the same size as the earth in the desktop view?
![Screen Shot 2022-09-08 at 3.40.56 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c556ec48-50bb-4a26-8262-e423e5cf1c17)

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Can we size the heart art, so it looks the same size as the earth in the desktop view?
![Screen Shot 2022-09-08 at 3.40.56 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c556ec48-50bb-4a26-8262-e423e5cf1c17)

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii let's use these two SVGs so that the strokes of the artwork are the same.
![charity.svg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b324babb-5db3-403b-b066-b2739fa01ffb)
![earth.svg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e229e400-0597-44a4-b8a6-e02d9a4388ee)

**Comment by oluwatunmiisheii** [comment]
Done @FanFanDAO

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO this is the link to the preview
https://popcorn-foundation-git-new-website-popcorn-dao.vercel.app/grants

**Comment by FanFanDAO** [comment]
Looks good to me.
