### ISSUE TITLE
Notification reskin

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1165]
## Description
We have the notification system and just need to ensure they are styled correctly according to the new branding. 

## Specific Acceptance Criteria
- Make sure the font sizes and weight follows our Figma file
- Make sure all color codes are correct

## Resources
Mainsite Folder (Figma) > Presentation 26072023 > 3X screen

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-08-29 at 6.54.27 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/4c224e50-3ff2-435f-b399-ab0b2e12c168)

**Comment by RedVeil** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/1165?planning-poker) with Zenhub @Ajiva-D @arne-z @ecmendenhall @oluwatunmiisheii

**Comment by RedVeil** [comment]
This is also in https://github.com/popcorndao/sweet-caramel/pull/1171
