### ISSUE TITLE
02 - Cards (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1175]
## Description
We are doing an MVP rebrand reskin process for our Grant site. Here you are looking at the cards.

Cards:
- Open Vote
- Challenge period
- Completed

## Specific Acceptance Criteria
- Fetch data accurately for info
- Reskin the layout of the cards & any infographic (Desktop & Mobile)

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
Eligible beneficiaries:
![card_eligible beneficiary.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/94692bef-77cb-46dd-8f38-7bee50da5cea)
Open vote, Challenge Period:
![card_openvote_challengeperiod.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a8e98b9b-9ce6-4cee-957b-fe884a7fba99)
Completed:
![card_completed.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/10ba8593-d74a-46b1-9fb2-b05f981ce744)

**Comment by RedVeil** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/1175?planning-poker) with Zenhub @Ajiva-D @arne-z @ecmendenhall @oluwatunmiisheii

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii, how can I see these cards in all of their different states?

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO 
![Screenshot 2022-09-21 at 10.22.47.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/021143ce-e698-43ee-b032-a8a937ec2f7d)

**Comment by FanFanDAO** [comment]
@anthonymartin @RedVeil This ticket looks good to me. The reason I tagged you is to bring to the attention that we can not view on the beta test link on the cards and therefore I have requested the engineer to show me screenshots from his localhost for the preview.
