### ISSUE TITLE
03 - Beneficiary Application Page (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1176]
## Description
We are doing an MVP rebrand reskin process for our Grant site. Here you are looking at the Beneficiary Application page.

## Specific Acceptance Criteria
- Fetch data accurately for all links
- Filter dropdown & Filter tags (Desktop & Mobile)
- Reskin the page (Desktop & Mobile)
- Load more functionality (Desktop & Mobile)

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Grant_Beneficiaries Applications_desktop.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/4d6ac54d-1157-467d-8f31-a7bb21c058a3)
![Grant_Beneficiaries Applications_mobile.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/bcf2da62-c237-4208-9e59-4ecb0264d104)
![Categories Filter.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/047eed42-1e5a-4899-9d9a-dbd8f1d14490)
![Grant_filter tags_mobile.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/fd6aad0e-1109-4b4e-b02b-d9df4f8f0adb)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO this is the [preview link](https://grants-nu.vercel.app/applications)

**Comment by oluwatunmiisheii** [comment]
[Uploading... brnrficiary_applications_web.png]

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii  Feedback: https://www.loom.com/share/45b17ad718334c7b9085041bc8ec5313

The default selected filter tag is in the wrong color and should not have a border. 
![Screen Shot 2022-09-20 at 4.37.27 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2c12b557-e755-41b7-b4a9-584853f6ddd0)

When it is the empty state, we do not show the dropdown for categories and filter tag for both desktop and mobile.
![Screen Shot 2022-09-20 at 4.41.36 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/56dbac55-4145-49c8-9a14-dc9ff72b95f2)

I will need to see mobile and desktop screenshots captured from the same link (https://grants-nu.vercel.app/applications) and please capture with the URL visible.

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO this is the loom link to how the beneficiaries application section looks like
[https://www.loom.com/share/d975830ec74544e3a01cd938eb6a8e47](url)

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Feedback:
1) Mobile filter tag is styled incorrectly. background code #827D69 Text color: #ffffff No border stroke
![Screen Shot 2022-09-21 at 3.47.33 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e87afbc1-2892-4830-bc62-9dd9ed69fac8)
![Screen Shot 2022-09-21 at 3.46.40 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3861d8ef-d275-4278-be5a-e3b0e391962e)

2)  "See more" button styled incorrectly. Comment given on other related tickets as well.

3) Logic for "See more" button: It should be invisible unless there are more cards to be shown. We do not need an inactive state. Please double check on both desktop and mobile.
![Screen Shot 2022-09-21 at 3.51.01 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/02d0e332-2de8-4df0-af34-6ffad586b3b9)

**Comment by oluwatunmiisheii** [comment]
[Uploading... Screenshot 2022-09-21 at 15.13.57.png]

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-21 at 15.15.33.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/ba34aa35-08c3-462b-804e-42b290937333)

@FanFanDAO

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO [Uploading... Screenshot 2022-09-21 at 15.20.10.png]

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-21 at 15.23.51.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/d4cefa73-38f0-4342-914a-5943bea7257c)
@FanFanDAO

**Comment by FanFanDAO** [comment]
@RedVeil Hey Leon, the last feedback looks good to me. Since we can't view this on the beta test link, the screenshot from his Localhost will represent the frontend result. We will need a final check before launch, but we are done on this ticket for now.
