### ISSUE TITLE
Add SwapZapper

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1179]
Since some of our vault assets are not crv-lp-token we need a second zapper contract that can simply swap needed tokens.
The new zapper should follow the same interface as the old one. Additionally Zapper.ts should choose one or the other zapper depending on the stableSwapAddress. If StableSwapAddress is address(0) we should use the swapZapper or otherwise we use the crv-lp-zapper.

**Comment by arne-z** [comment]
TODO 2 tests are still failing:
- [ ] VaultsV1Registry.t.sol#test__view__getVaultAddressNotRegisteredReverts
- [ ] VaultsV1Factory.t.sol#test__deployVaultV1NotOwnerReverts

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/1166
