### ISSUE TITLE
Swap out connors foundry with normal foundry

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1181]
The original cheatcodes added by connor to his fork of foundryare now implemented into normal foundry. Therefore we have new features faster if we just use the normal foundry version. 

This means we need to update:
 - [x] foundry.toml
 - [x] all tests in /test/forge/*
 - [x] hardhat/package.json
 - [ ] .github workflows

**Comment by RedVeil** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/1181?planning-poker) with Zenhub @Ajiva-D @Amirjab21 @arne-z

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1198
