### ISSUE TITLE
'Coinbase wallet' option is missing from Available Wallets

### ISSUE THREAD

**Issue by mefuru** [popcorndao/sweet-caramel#1182]
**Describe the bug**
If you disconnect all your wallets and then re-enter [https://popcorndao.finance/](https://popcorndao.finance/), there is no option for Coinbase Wallet.

**To Reproduce**
1. Go to https://popcorndao.finance/
2. Click on 'Connect Wallet'
<img width="963" alt="image" src="https://user-images.githubusercontent.com/3315297/188454348-e97b3c24-afca-46b3-b666-c4219396ff90.png">

**Expected behavior**
I expect to see Coinbase wallet as an option

**Desktop (please complete the following information):**
 - OS: MacOS
Brave Version 1.42.97, Chrome Version 104.0.5112.101 and Safari

**Comment by RedVeil** [comment]
@FanFanDAO Please check if you can reproduce this error

**Comment by RedVeil** [comment]
Couldnt reproduce the error across multiple systems
