### ISSUE TITLE
07 - Popover: Congrats Staked (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1190]
## Description
We are doing an MVP rebrand reskin process for our Grant site. Here you are looking at the popover for when the user staked POP and are now ready to participate in the Binary voting process.

## Specific Acceptance Criteria
- Use JSON or SVG images for faster load time
- Fetch data accurately for any applicable info
- Reskin the layout of the popover (Desktop & Mobile)

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Congrat Staked.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/96732342-0931-4de4-a18c-7dfaea441453)
![Congrat Staked.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/596de9e2-a616-4c8d-a51e-479187d5964b)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-23 at 14.16.15.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/a1e92948-97ad-479b-8c12-8d848ed39079)
@FanFanDAO

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-23 at 14.20.04.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/d813b4e5-b56c-4232-ab40-4fcf21c9ce37)
@FanFanDAO

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii  Thank you for the above screenshot.

@anthonymartin Hi Anthony, I am tagging you and assigning you since I checked the frontend UI, and they seem good on Adenuga's screenshot (above this comment). We are viewing Adenuga's Localhost because the popover can not be triggered at this time on the beta preview link. Also, I assume you will need to review the code. However, please assign Arne if you think he can take over and let me know.
