### ISSUE TITLE
06 - Popover: Stake POP (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1191]
## Description
We are doing an MVP rebrand reskin process for our Grant site. Here you are looking at the popover for staking POP if the user has never staked any POP before while trying to participate in our voting process. This popover gets triggered by the Stake to Vote button on the voting card.

## Specific Acceptance Criteria
- Use JSON or SVG images for faster loading
- Fetch data accurately for all info
- Reskin the layout of the popover & any infographic (Desktop & Mobile)

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Stake.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/77c07963-1bc0-4f84-ac51-c07e987090f6)
![Stake.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/51cf00ee-b406-4d72-933b-c169728ad1a9)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-22 at 19.23.24.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/7d464f08-6d67-49ab-9c77-11f718b719af)
@FanFanDAO

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii  Thank you for the above screenshot.

@anthonymartin Hi Anthony, I am tagging you and assigning you since I checked the frontend UI, and they seem good on Adenuga's screenshot (above this comment). We are viewing Adenuga's Localhost because the popover can not be triggered at this time on the beta preview link. Also, I assume you will need to review the code. However, please assign Arne if you think he can take over and let me know.
