### ISSUE TITLE
08 - Popover: Accept or Reject Application (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1192]
## Description
We are doing an MVP rebrand reskin process for our Grant site. Here you are looking at the popover for accepting or rejecting a beneficiary application during the binary voting process. This popover gets triggered when the user clicks on the Accept or Reject button.

## Specific Acceptance Criteria
- Use JSON or SVG images for fast loading
- Fetch data accurately for info
- Reskin the layout of the popover (Desktop & Mobile)

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Accept Application.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/32da2275-bf13-4d31-83d6-fd8f3f2c45b8)
![Accept Application.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ba3cffe7-bd8a-409f-a9ec-b9410021c37c)
![Reject Application.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b666d13b-9df4-4761-9daf-c3858cdc73ac)
![Reject Application.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/5d303807-9430-4d69-b344-3f1849e881ec)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-23 at 15.49.36.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/2ce1f8c7-87cc-47c4-96dc-5eb15662deff)

![Screenshot 2022-09-23 at 15.50.47.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/9461112a-7b90-4481-941b-8503260b1a58)
@FanFanDAO

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-23 at 15.51.42.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/f95d31ea-e32f-4950-a56a-707e4a0b9c93)
![Screenshot 2022-09-23 at 15.52.07.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/46a48827-0ef1-407f-b7df-fc53e290eb80)

@FanFanDAO

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Within the message, the name of the beneficiary will change depending on the beneficiary. Is this logic set up with the copy? ![Screen Shot 2022-09-26 at 1.24.14 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/61d0a26b-7f73-434e-9693-08f475fb6e9a)
![Screen Shot 2022-09-26 at 1.24.12 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/75c402e5-327b-4d83-9ec7-4770c0a09702)

**Comment by oluwatunmiisheii** [comment]
Yes @FanFanDAO

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Thank you for the above screenshot.

@anthonymartin Hi Anthony, I am tagging you and assigning you since I checked the frontend UI, and they seem good on Adenuga's screenshot (above this comment). We are viewing Adenuga's Localhost because the popover can not be triggered at this time on the beta preview link. Also, I assume you will need to review the code. However, please assign Arne if you think he can take over and let me know.
