### ISSUE TITLE
09 - Popover: Vote Accepted or Rejected (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1193]
## Description
We are doing an MVP rebrand reskin process for our Grant site. Here you are looking at the popover for when the user voted to accept or reject during the binary voting process. This popover gets triggered upon clicking the Accept or Reject button on the previous popover from within the "Accept Application" OR "Reject Application" popover.

## Specific Acceptance Criteria
- Use JSON or SVG images for fast loading
- Fetch data accurately for info
- Reskin the layout of the popover (Desktop & Mobile)

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Vote Accepted.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/6f6e41d4-47c4-4f1d-8a6f-b8ae974aa1a4)
![Vote Accepted.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c83fd950-a887-4fa4-9098-229992488a40)
![Confirm Rejected.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a77e1aa7-6dcf-4d8b-a143-640c7094094f)
![Confirm Rejected.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/92de8541-dfc6-4569-bec4-df5e56ef8e02)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-23 at 12.54.29.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/8a02b02e-7e98-4717-972d-a3b727a9dee6)

@FanFanDAO

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-23 at 14.01.59.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/967b5973-2ff3-46b2-9062-69fbc494716a)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-23 at 14.03.39.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/9c94a5ed-00c6-4a5d-8918-83b156adba9a)

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii, is the logic set up for the message? Why does it say from Wikipedia?

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO this is the logic
`You have rejected the proposal of "${proposal?.application?.projectName}" beneficiary from ${proposal?.application?.organizationName}. If a majority of the community votes to reject this beneficiary, they will no longer be eligible.`,

here, we specify the projectName of the and the organazationName

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Thank you for the above screenshot.

@anthonymartin Hi Anthony, I am tagging you and assigning you since I checked the frontend UI, and they seem good on Adenuga's screenshot (above this comment). We are viewing Adenuga's Localhost because the popover can not be triggered at this time on the beta preview link. The text logic has been defined above. Also, I assume you will need to review the code. However, please assign Arne if you think he can take over and let me know.
