### ISSUE TITLE
11 - Eligible Beneficiary Landing (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1195]
## Description
We are doing an MVP rebrand reskin process for our Grant site. Here you are looking at the landing page for viewing the eligible Beneficiaries. The top nav and footer should have been done.

## Specific Acceptance Criteria
- Fetch data accurately for all links
- Page layout of the page (Desktop & Mobile)
- Filter dropdown function (Desktop & Mobile)
- Empty state (Desktop & Mobile)

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Landing.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/82b08ce9-019b-4e9f-a263-7097d2240527)
![Landing.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c4c88151-3ea8-4db9-abad-c6cd35688b57)

**Comment by oluwatunmiisheii** [comment]
![eligible-beneficiaries.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/d716404c-371f-4b23-b86b-1b944278b3ce)[Uploading... eligible-beneficiaries-mobile.png]

**Comment by oluwatunmiisheii** [comment]
![eligible-beneficiaries.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/d716404c-371f-4b23-b86b-1b944278b3ce)[Uploading... eligible-beneficiaries-mobile.png]

**Comment by oluwatunmiisheii** [comment]
![eligible-beneficiaries.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/d716404c-371f-4b23-b86b-1b944278b3ce)[Uploading... eligible-beneficiaries-mobile.png]

**Comment by oluwatunmiisheii** [comment]
![eligible-beneficiaries.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/d716404c-371f-4b23-b86b-1b944278b3ce)[Uploading... eligible-beneficiaries-mobile.png]

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii I will need to see the screen capture for when the cards are populated and under the same preview URL. 

For empty stake, we need to remove the categories filter for desktop and mobile

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO i attached a screen capture above

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO this is how the desktop and mobile view looks like
[https://www.loom.com/share/edf6ceb12a3e4f988a70e744bb6986d1](url)

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Feedback:
1) The mobile categories filter should be the Select scroll menu function. I have informed about the styling and tagged you on Figma earlier.
2) See more button is styled in correctly and should filled to width.

**Comment by oluwatunmiisheii** [comment]
The mobile categories has already been updated to the scroll menu, this is no longer the wheel picker. It is exactly what we have on .finance @FanFanDAO

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-21 at 15.26.35.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/694c1f16-3b86-4052-885d-405821b9f249)

@FanFanDAO

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-21 at 15.29.28.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/fc92dbbe-6a2a-406e-9929-2c0a4d7abcab)

@FanFanDAO

**Comment by FanFanDAO** [comment]
@RedVeil Looks good to me from Adenuga's screenshot. We will need a final check when the MVP is done.
