### ISSUE TITLE
13 - Create Proposal Landing (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1197]
## Description
We are doing an MVP rebrand reskin process for our Grant site. Here you are looking at the landing page to create a proposal. It gives the user all the essential info before creating an application.

## Specific Acceptance Criteria
- Fetch data accurately for all links
- Page layout of the page (Desktop & Mobile)
- "Start Application"-button links to the "Create Application"-Page1
- We don't need to include the Popcorn Foundation Social Impact Questionnaire line as the doc is not done yet.

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Create Project.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/fef1f088-a9ad-4a09-afe4-6870759f7b73)
![Profile.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b4f6e621-4659-455d-b3ca-180fee376f0f)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback:
Mobile top nav is weird
![Screen Shot 2022-09-19 at 5.26.28 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/bc0c6310-2561-4c13-a0fb-8c20f0b5e8e4)
Let's space out more for this section
![Screen Shot 2022-09-19 at 5.28.51 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f31738c3-e241-4178-a1ab-be3fcd1dd447)

**Comment by Ajiva-D** [comment]
@FanFanDAO the mobile nav is not part of this ticket, it's part of the grants landing page ticket. @oluwatunmiisheii is working on that and I don't think it's done yet

**Comment by FanFanDAO** [comment]
@Ajiva-D Got it. Can you fix the spacing?

**Comment by Ajiva-D** [comment]
@FanFanDAO this is the link

**Comment by FanFanDAO** [comment]
@Ajiva-D Everything seems good. We need to make sure the connect wallet and start your application buttons in mobile are filled to the width of the container. 
![Screen Shot 2022-09-20 at 2.19.07 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/834b55f0-5688-4e55-80aa-9be526781702)
to:
![Screen Shot 2022-09-20 at 2.18.39 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9bd293ec-7fde-4b33-a063-9cf2d5e6411e)

**Comment by Ajiva-D** [comment]
This is done now @FanFanDAO
