### ISSUE TITLE
15 - Create a proposal flow Step 2 & Step 3 (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1200]
## Description
We are doing an MVP rebrand reskin process for our Grant site. Here you are looking at the create proposal flow steps 2 & 3. David has done all the functions for this page. This ticket is really about the reskinning process and working with our new grid.

## Specific Acceptance Criteria
- Fetch data accurately for all links
- Page layout of the page (Desktop & Mobile)
- Filter selector: Proposal Category (Desktop & Mobile)
- the next button is inactive unless the user has completed the mandatory items

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Step 2.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/fdb910ab-f9b0-453d-b0ec-d05adadace43)
![Step 2.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e5e745d3-73c2-479d-bc95-87195de1701e)
![Step 3.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/7b59b05d-3dab-4f85-a89e-cb11f3dcba25)
![Step 3.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9b24af14-d527-4198-90c8-be781d3b0f11)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://grants-om6st9myn-popcorn-dao.vercel.app/

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback
Step 2 (Mobile): "2 Proofs" should move to the left edge when it is highlighted. This applies to Steps 3 and 4. Also, we are missing left and right padding. Style the spacing for the "Back" and "Next" buttons correctly just like our Figma design.
![Screen Shot 2022-09-19 at 6.55.21 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/aa067743-41cc-4cc2-a0b3-e51ce273c480)

The correct image reference for the Step 3 desktop view has been updated. Please reference this:
![Step 3.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/263fbc4a-cd1b-4a39-85cd-6ab0b374ed5e)

Step 3 (Mobile): "3 Impact Reports" should be on the left edge when highlighted. MWe are missing left and right paddings. Style the spacing for the "Back" and "Next" buttons correctly.
![Screen Shot 2022-09-19 at 6.23.11 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/356ab4b5-ef4f-47a2-84ea-e95a871d5864)

**Comment by FanFanDAO** [comment]
@Ajiva-D Impact report upload function keeps showing the upload sign, but no successful upload has been achieved.

**Comment by FanFanDAO** [comment]
@Ajiva-D Wrong color styling for the next button.
![Screen Shot 2022-09-26 at 2.15.17 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/daf2034d-eb7a-443b-9513-b653953f2bd1)

**Comment by Ajiva-D** [comment]
@FanFanDAO I don't think this is the case. Our buttons have a hover state, and on mobile phones the hover state of buttons reflect after being touched. So the button color is just the hover state. That's the browser behaviour and not from us.

**Comment by FanFanDAO** [comment]
@Ajiva-D got it. :) 
@anthonymartin looks good to be on mobile and desktop: https://grants-nu.vercel.app/apply/form
