### ISSUE TITLE
16 - Create a proposal flow Step 4 (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1201]
## Description
We are doing an MVP rebrand reskin process for our Grant site. Here you are looking at the create proposal flow step 4. David has done all the functions for this page. This ticket is really about the reskinning process and working with our new grid.

**Step 4:**
- Empty state
- Upload state
- Fail to upload state
- !! Does not include the upload progress for now !!

## Specific Acceptance Criteria
- Fetch data accurately for all links
- Page layout of the page (Desktop & Mobile)

## Resources
Please ask the PM for the Figma link to the source file.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Empty State.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/aa03b08c-0e3d-44ed-8cb2-722361391c48)
![mobile_Empty State.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/fb7d6606-5c39-4952-b058-54150d8855ee)
![Uploading.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/4836718d-6a44-4ecb-8925-336e192cf527)
![mobile_Uploading.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8bf8f702-0791-437e-bbca-28bb88635113)
![Reupload.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/0f259bdd-d53f-4ec5-9d8c-ada10ca1226b)
![mobile_Uploading.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ba1fd49e-ae26-43c7-b574-475103583d75)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://grants-om6st9myn-popcorn-dao.vercel.app/

**Comment by FanFanDAO** [comment]
@Ajiva-D I couldn't upload an image to review the UI here.
![Screen Shot 2022-09-19 at 7.12.08 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/7a8fe6a6-6bfb-49de-87c4-8285d966b326)

**Comment by Ajiva-D** [comment]
@FanFanDAO yes uploading isn't possible on the preview yet, I'll ask Leon to see if it can be done.

**Comment by Ajiva-D** [comment]
@FanFanDAO ![Screenshot 2022-09-20 at 14.37.05.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/e7cc57da-feb6-474d-84bb-58053cd10893) ![Screenshot 2022-09-20 at 14.38.02.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/0c00c1a5-7aa8-488f-9217-ae74aca71ea8)

**Comment by FanFanDAO** [comment]
@RedVeil Based on David's screenshot provided, it seems good to me. However, we should be able to preview and have a whole run-through with the beta test link before launch. So for now, I will move this ticket to Done.
