### ISSUE TITLE
.network - Move the LPs with the BTR (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1230]
Let's move the LPs with the BTR since we added: "POP Staking" on (.network). It breaks the graphic balance from almost touching the yellow stroke art.

![Screen Shot 2022-09-14 at 10.21.49 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9284422d-170a-47ea-a738-50a6e7c92701)

**Comment by Ajiva-D** [comment]
@FanFanDAO this is actually the .network page

**Comment by FanFanDAO** [comment]
@Ajiva-D On mobile, the yellow stroke is misplaced.
![Screen Shot 2022-09-14 at 3.17.51 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/049b6f92-46b7-4c15-a318-54ee684ebde3)
