### ISSUE TITLE
Refactor InputToken + TokenSelection to work on all pages

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1232]
We currently have two different ways of selecting Token. Either by a key in an object (butter,3x) or by just directly setting a `Token` in state. This is also the root cause why we have TokenInput and TokenSelection in one half of the app (staking,sweetVaults) and ButterTokenInput + SelectToken in the other. 

We need to refactor these components to work universally across the app.

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/1255
