### ISSUE TITLE
Reskin Emission dashboard ASAP!

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1233]
## Description
Reskin Emission dashboard ASAP!

## Criteria
Mobile Only. From Anthony "I think it just needs a line break after the title and the date filter, with some margins on the side"

## Reference
https://www.figma.com/proto/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=2869%3A55914&scaling=min-zoom&page-id=201%3A46786&starting-point-node-id=2869%3A55914

Link: https://emissions-dashboard.popcorn.network/

**Comment by anthonymartin** [comment]
the idea is to polish this for *mobile*:

* needs a line break after the title and the date filter with some margins on the side

colors and things can be changed after the above is completed

**Comment by FanFanDAO** [comment]
@anthonymartin We fixed the spacing and margin issues.
https://github.com/popcorndao/workspace/pull/915

**Comment by FanFanDAO** [comment]
https://deploy-preview-915--emissions-dashboard.netlify.app/
Looks good to me.
