### ISSUE TITLE
22 - Rsearch message preset for when sharing an URL on Whatsapp or Telegram

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1236]
## To-do
Find out how we can share a preset message on messengers such as Whatsapp and telegram when sharing an URL.

**Comment by FanFanDAO** [comment]
@RedVeil 
Can someone look into this? 
https://ogp.me/

I read this:
https://stackoverflow.com/questions/19778620/provide-an-image-for-whatsapp-link-sharing

**Comment by Ajiva-D** [comment]
Alright, sure

**Comment by Ajiva-D** [comment]
WhatsApp and Telegram have links with query params for the url you intend to share and the proposed text message, just like all the other social networks. The preview image will be generated from the url you send and we already know how to add social share cover images to our links as we've done so for .network and .finance.

**Comment by FanFanDAO** [comment]
@Ajiva-D Got it.
