### ISSUE TITLE
Take down image with the tree (Foundation)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1238]
## Description
This tree image we are using needs to be removed for now due to licensing discussion. However, we are in the process of looking for the next best-fit image for this area.

## Specific Acceptance Criteria
- remove in all places where this image appears
- make sure this component can be brought back easily upon finding the next best fit. Hide it for now.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-09-15 at 11.51.28 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/965e3655-9cfc-4ffb-8e89-d98fff47c3f3)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO this is the preview link
https://popcorn-foundation-git-new-website-popcorn-dao.vercel.app/
