### ISSUE TITLE
Add support for second RewardsEscrow contract in rewards page

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1244]
We will add a second RewardsEscrow contract to the frontend for vaults. For this we must make sure that the rewards page can aggregate and interact with both contracts at the same time. 

use this branch as the base: feature/vaultsV1-controller-setZapper

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/1281

**Comment by arne-z** [comment]
This is built to be backward compatible so it can be merged before the new VaultsRewardsEscrow contract is merged.
