### ISSUE TITLE
Add VaultsRewardsEscrow contract to the deployment scripts

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1245]
Add a second RewardsEscrow contract to the deployment and it add it to the contractRegistry as "VaultsRewardsEscrow".
Add it to exportAddresses.js and ContractAddresses in utils/types as vaultRewardsEscrow.

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/1267
