### ISSUE TITLE
Sweet Vault Updates (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1256]
## Description/Traceback
We need to polish up the design of sweet Vaults before going live with it. This ticket will address multiple small issues that came up.

1. Currently "cursor-pointer" is shown across the whole Sweet Vault. It should only be seen on parts than one can actually interact with. (Deposit/Withdraw toggle, buttons, input fields and the top part of the card that hides it)
2. The Sweet Vault card should not get larger on hover once its expanded
3. The expanse animation of the Sweet-Vault needs to be adjusted on the last item so that the button border and pagination dont move underneath the card elements.

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO this is the preview link, as discussed in the chat on slack, you would be unable to test from here
[https://sweet-caramel-git-feat-sweet-vaults-update-popcorn-dao.vercel.app/localhost/sweet-vaults](url)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO this is the loom link
[https://www.loom.com/share/3df1f473f748417d9607a0655dff0aea](url)
