### ISSUE TITLE
Use Defillama for token prices

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1259]
Some of our price estimate logic does not work correctly right now. Specifically, this concerns the calcOutputAmount function.
The assumption that input token to LP token is roughly a 1:1 ratio no longer works.

We instead need to use the Defillama API to find the estimate.
API returns some unexpected data sometimes so we will need to filter the API response.

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1337

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/1359
