### ISSUE TITLE
One line for the name "G-Uni" and make sure input field has a fix height

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1264]
## To-do
Make G-Uni one line. The input field is fixed in height (56px). It should not be distorted.

## Image reference
![Screen Shot 2022-09-26 at 4.48.50 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/724071e9-20af-4014-89b2-500816fecd54)

**Comment by Amirjab21** [comment]
PR:https://github.com/popcorndao/sweet-caramel/pull/1288

**Comment by FanFanDAO** [comment]
@RedVeil can you code check and close this? xox
