### ISSUE TITLE
Bug - Claim Popover (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1266]
## Description
This ticket is about the popover when the user clicks on the "Claim" button under Your Batch. The current live popover is not properly done so please refer to the Figma file and reference image below.
​
Area of concern:
- 3X
- Butter

## Specific Acceptance Criteria
- Use nextJS or SVG images (faster load)
- Selection should be saved automatically when a user interacts with this popover
- Tags should work properly with select states
- Cancel: It means to leave the popover and revert any adjustments made
- Claim: triggers the claim process and Metamask should pop up
- On-clicked tooltip info should be the same as our current existing Slippage
- Add "(Default: 1%)" next to the Slippage Adjustment header
- Layout (Desktop & Mobile)

## Resources
I will tagged you in Figma.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-09-26 at 5.58.56 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e413b7b8-fdc7-47af-a1b0-2fda4899d671)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO 
https://sweet-caramel-git-feat-claim-popover-update-popcorn-dao.vercel.app/ethereum/set/3x
