### ISSUE TITLE
24 - Landing page update (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1268]
## Description
Anthony has made a request to update this page and the new design can be viewed in the reference images below.
​
## Specific Acceptance Criteria
- Follow the layout on the latest design (Desktop & Mobile)
- Add the missing Learn how it works button on mobile 
- Add mobile Step 1 to 3 carousel ( This style exists and we are using it on the 3X and Butter pages.)
- Update footer with text link "Create proposal" under Links (Desktop & Mobile)

## Resources
Ask the PM.

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Landing Page_d.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a9c6a213-e9f2-40cb-8e64-b59b3cd142f3)
![Landing Page.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/cc857371-e8cf-470d-8749-30d956e45713)
![Screen Shot 2022-09-27 at 4.12.35 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b007a435-942f-4233-af63-0a4d20e77e08)

**Comment by FanFanDAO** [comment]
@Ajiva-D Desktop and mobile updates: (I have tagged you in the Figma file on these screens)
![Screen Shot 2022-10-05 at 12.03.51 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/32f0667c-9e41-43aa-86c3-c640719b77fe)
Top nav update: (Popcorn Grants refers to the home page)
![Screen Shot 2022-10-05 at 12.04.06 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/fa373ebf-60ce-423e-a574-a935be5f3c1f)
Footer update:
![Screen Shot 2022-10-05 at 12.04.22 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e7c34e84-dbdd-4d7e-a1de-8acd8e19569b)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://grants-nu.vercel.app/

**Comment by FanFanDAO** [comment]
@Ajiva-D 

1) This ticket also includes the update for the top nav and footer. I don't think they are updated.

2) Feedback: https://www.loom.com/share/1c8dd3b947334f3eb459082efd8171b6
Also, since I can't view the states with cards being populated on desktop and mobile and check on all filters. I need to see a Loom video explainer of this.

**Comment by Ajiva-D** [comment]
@FanFanDAO where will the FAQ link too?
Also, no change has been made to the cards or filter so I do not think there's a need for a loom video to show that since it has already been done before.

**Comment by Ajiva-D** [comment]
@FanFanDAO where will the FAQ link too?
Also, no change has been made to the cards or filter so I do not think there's a need for a loom video to show that since it has already been done before.

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback:
![Screen-Shot-2022-10-07-at-12.38.34-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f3479aa9-fad1-49b9-bd1c-20fc8ab53721)
![Screen-Shot-2022-10-07-at-12.39.57-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c061f2af-dc9c-49d0-a1be-1b43afdfda24)
![Screen-Shot-2022-10-07-at-12.36.50-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/76a57a81-115e-43ab-a9b8-0dce3904a188)

**Comment by Ajiva-D** [comment]
All updated

**Comment by FanFanDAO** [comment]
@RedVeil The UI looks good. I will have you check the code now.
