### ISSUE TITLE
[Code Quality] Move Email adress regex to util

### ISSUE THREAD

**Issue by arne-z** [popcorndao/sweet-caramel#1271]
I'd prefer the email address Regex to be somewhere in utils where it can be referenced by more parts of the code, otherwise, at some point, we might end up with 3 instances of it floating around in the codebase.
Either as a `const EMAIL_ADRESS_REGEX` or as a `function isEmailAdress(test: string): bool`
![image.png](https://images.zenhubusercontent.com/5c6e9b98b3d46374d6a0d6b3/3b5e88d4-08e2-4155-a749-5bda83cc59c5)

**Comment by thinktrans** [comment]
If I may, I would like to request you to not put in the regex as decided. It invariably leaves the Internationalized Email addresses at bay. If possible, keep it as simple as this:
`<e-mail local part>@<domain name>`
Which can be implemented as 

For `<e-mail local part>` - Follow the guidelines by the "Universal Acceptance Steering Group" - UASG-026 - https://uasg.tech/download/uasg-028-considerations-for-naming-internationalized-email-mailboxes-en/

For `<domain name>`, you can follow any domain validation methodology using standard libraries, depending on your programming language. For the recent studies on the subject, follow the document UASG-018A - https://uasg.tech/download/uasg-018a-ua-compliance-of-some-programming-language-libraries-and-frameworks-en/.

**Comment by RedVeil** [comment]
@RedVeil @anthonymartin Should we include this as a new ticket?

**Comment by anthonymartin** [comment]
sure, I'd follow @thinktrans 's advice on this one. makes sense. Thank you for chiming in!

**Comment by anthonymartin** [comment]
@RedVeil ^^
