### ISSUE TITLE
[Code Quality] Remove redundant declaration of filtervalues enum

### ISSUE THREAD

**Issue by arne-z** [popcorndao/sweet-caramel#1275]
we've already exported this exact enum before in the beneficiaryFilter component, it should only be exported in one place and imported everywhere else. Consider either moving it to a shared file or deciding it belongs to the filter and exporting only from there.
![image.png](https://images.zenhubusercontent.com/5c6e9b98b3d46374d6a0d6b3/d469952f-bb29-4eba-8981-5caeaeb29561)

**Comment by Ajiva-D** [comment]
We actually weren't even using it on this page so I'm just removing it from here
