### ISSUE TITLE
Copy changes for popover "A Vesting Record has been created"

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1279]
## To-do
Change the header to "Sweet!" on desktop and mobile popovers

## Reference
![Screen Shot 2022-09-28 at 4.32.44 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/de106f20-42c4-4769-bbdf-c429aa5c2dfa)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO 
https://sweet-caramel-git-chore-update-rewards-modal-title-popcorn-dao.vercel.app/

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-28 at 17.23.23.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/cfbea8f3-5794-43ba-ac14-e71631f0a0ca)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-09-28 at 17.26.37.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/1ed9c7dd-5b7c-4b47-a7e9-bb52292ab7b5)
