### ISSUE TITLE
Use the right circular logo icon for "Your Staking Rewards" cards on all Staking Detail Pages 

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1285]
## Description
Please replace the circular POP token icon for all Staking contract detail pages in both Ethereum and Polygon networks.

Staking detail page:
- 3X
- Butter (v2)
- Popcorn
- Arrakis
- Sushi
​
## Specific Acceptance Criteria
- replace with the right nextJS images /SVG image (faster load)
- make sure it displays correctly on desktop and mobile before moving to review
​
## Resources
![icon_circle_Yellow_192x192.svg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e461285c-fec9-4b12-8dfa-fbb80809fa9c)

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-09-30 at 5.37.49 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e6d4fa0a-08ff-46fd-9e30-64fc4ae3103f)

**Comment by Ajiva-D** [comment]
@RedVeil please can this be pushed to prod?
