### ISSUE TITLE
[Component Refactor] VestingRecord - Connected Component

### ISSUE THREAD

**Issue by arne-z** [popcorndao/sweet-caramel#1327]
The VestingRecord is a connected component receiving a vestingRecord by ID and uses hooks to fetch data for the record, as well as handles interactions for it.

**Comment by Amirjab21** [comment]
This would mean an increase in the number of blockchain RPC calls as we would have to be doing each vesting record call separately. 

Currently, on the rewards page, it does a single call to get all vesting records data and then maps this onto the <VestingRecordComponent />

@arne-z  is this an improvement or should it stay as it is on the rewards page?

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1382
