### ISSUE TITLE
Integrate a "Newsletter Sign up" popover to our Dapp

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1334]
## Description
To boost our email sign-up, we are integrating a popover upon landing on the Dapp. This popover can be triggered by the top nav button as well. Please look at the reference image below. 
​
## Specific Acceptance Criteria
- Layout and functions of the popover
- Add the "Newsletter Sign up" button to the top nav (Desktop and Mobile menu)
- The popover should be triggered 5 seconds after the website is fully loaded
- If the user clicks on our feature video, the popover should be presented 5 seconds after the video has been paused
- We agreed to keep a tracker in the localStorage, which we set to true after the first time the modal opens

## Resources
Ask the PM

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Application_Popover_Landing page_D.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8e7aeaa3-7799-46f0-b4c8-2758a304fa9a)
![Application_Landing page_D V1.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/35986b72-cca0-4f7a-90eb-2217718d57fe)
![Screen Shot 2022-10-14 at 9.49.15 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1342e4e4-7d88-4f61-baaf-8dd283c6076f)
![Screen Shot 2022-10-14 at 9.49.48 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2be681e7-cb76-4905-88d5-b8e35b126786)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO will the popover show by default the first time a user lands on the landing page or everytime they navigate to the landing page?

**Comment by FanFanDAO** [comment]
@Ajiva-D @RedVeil Good question above! 
Can we identify IP addresses and use that to lessen the trigger for frequent visitors? 
If not, can you speak to Leon about the best solution? For e-com, some promote are shown randomly or every time ( e.g. subscribe to view more)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO here is the [preview link](https://sweet-caramel-git-feat-newsletter-update-popcorn-dao.vercel.app/)

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Feedback, button is styled wrong.
![Screen Shot 2022-10-13 at 3.23.04 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3f91844d-cf70-405f-aca5-7da0db085f8b)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO 
[](https://sweet-caramel-git-feat-newsletter-update-popcorn-dao.vercel.app/)

**Comment by FanFanDAO** [comment]
@RedVeil It looks good from the preview link. Can you check the code and push it live? this is a priority requested by Michael.

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Hi Adenuga, the popover was not triggered in the mobile version.

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO mobile CTA added[ preview link](https://sweet-caramel-git-feat-newsletter-update-popcorn-dao.vercel.app/)

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii Please remember to move your ticket when you have finished the update. Feedback:
![Screen-Shot-2022-10-17-at-10.50.36-AM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/4253346e-aac8-4ab2-9bb5-2cb1b2a7bec1)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO 
https://sweet-caramel-git-feat-newsletter-update-popcorn-dao.vercel.app/

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii please fix asap.
![screen-shot-2022-10-17-at-4.07.17-pm.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/79252fb8-8a8b-4ddf-9ed5-1aff1cb7c300)

**Comment by FanFanDAO** [comment]
@RedVeil @oluwatunmiisheii All good to me from this PR link: https://sweet-caramel-git-feat-newsletter-update-popcorn-dao.vercel.app/

Leon: can you check the code and push this?
