### ISSUE TITLE
Multicall3 for VaultsV2

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1344]
Combine multiple automatic transactions into 4 different functions in a stateless router contract. Addresses of used Zap, Asset , Vault and Staking contract should be passed in as params. We should validate that the passed in asset matches the asset of the chosen vault.

- [x] Zap and Stake
- [x] Unstake and Zap
- [x] Deposit and Stake
- [x] Unstake and Withdraw

**Comment by SharifElfouly** [comment]
I created an example for each of the 4 tasks: https://github.com/popcorndao/sweet-caramel/blob/feature/muticall-v3/packages/utils/src/multicallV3Encoder.ts 

fyi: @RedVeil

**Comment by SharifElfouly** [comment]
The latest implementation: https://github.com/popcorndao/sweet-caramel/blob/feature/ds-proxy-multicall/packages/hardhat/test/DsProxyMulticall.test.ts

**Comment by SharifElfouly** [comment]
The PR: https://github.com/popcorndao/sweet-caramel/pull/1399/files
