### ISSUE TITLE
Error with our page loader from within the Staking Detail Page

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1349]
## Description
The loader cards are off the page and do not match the layout from within the Staking Detail Page. The reference image is attached below.
​
## Specific Acceptance Criteria
- Please match the layout of the loader cards in proportion and in the same position as the actual contents (Desktop & Mobile)
- Please make sure this is updated on new.popcorndao.finance (Desktop & Mobile)
- Please provide video attachments to prove the update (Desktop & Mobile)

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![screen_shot_2022-10-20_at_1.13.42_pm.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/66cd8d04-9c65-420b-8dc9-f9ff5c25e925)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO can you add the affected page url?

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii 
https://www.popcorndao.finance/ethereum/staking/pop
https://www.popcorndao.finance/ethereum/staking/0x27A9B8065Af3A678CD121A435BEA9253C53Ab428
https://www.popcorndao.finance/ethereum/staking/0x584732f867a4533BC349d438Fba4fc2aEE5f5f83
https://www.popcorndao.finance/ethereum/staking/0x633b32573793A67cE41A7D0fFe66e78Cd3379C45
https://www.popcorndao.finance/polygon/staking/0xe6f315f4e0dB78185239fFFb368D6d188f6b926C
https://www.popcorndao.finance/polygon/staking/0xd3836EF639A74EA7398d34c66aa171b1564BE4bc

Additionally, verify the position of these pages and send each screenshot on all pages when submitting this ticket for review. Thank you! 

https://www.popcorndao.finance/ethereum/set/3x
https://www.popcorndao.finance/ethereum/set/butter

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-10-26 at 10.40.39.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/dec64101-3724-48d9-80cc-845fdbcd6bdd)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-10-26 at 10.42.56.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/18a2fe83-2625-4a1b-91e6-9c4256d10c9c)

**Comment by oluwatunmiisheii** [comment]
[Uploading... Screenshot 2022-10-26 at 10.44.21.png]

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-10-26 at 10.45.16.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/f5fb4e12-7dfb-4760-8d51-8bc53ccf81f9)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-10-26 at 10.47.54.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/0654f55a-6ed8-4d9c-8b25-747ec8b16b5a)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-10-26 at 10.51.00.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/9c12bca9-3179-43d3-8aac-cf2b1f87f2ab)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-10-26 at 10.53.13.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/995107e9-8aef-4cd3-a5e5-0d99bc778741)

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-10-26 at 10.54.10.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/9ed7d519-cff6-4ed5-8091-0a24149c98f4)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO i attached all the images, tested on my small laptop and big monitor, could not replicate.

**Comment by FanFanDAO** [comment]
@anthonymartin Based on Adenuga's verification and per the given URL above, all loaders are in the right position.

**Comment by anthonymartin** [comment]
@oluwatunmiisheii @FanFanDAO  this happens specifically on the pop staking detail page on wide screen monitor

**Comment by oluwatunmiisheii** [comment]
@anthonymartin can you share a video and the dimension of the monitor if possible, so i can easily trace and fix

**Comment by oluwatunmiisheii** [comment]
![Screenshot 2022-11-04 at 13.52.01.png](https://images.zenhubusercontent.com/630ca9d8e53ae31ee804b6f2/08bb2a82-700c-48ee-9728-f7198c02dbb0)

@anthonymartin  @FanFanDAO

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO 
https://sweet-caramel-git-fix-staking-loading-spinner-popcorn-dao.vercel.app/ethereum/staking/pop

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii one miss alignment
![Screen Shot 2022-11-04 at 2.49.13 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c0e8302a-8507-4495-8eea-8f7222cdae35)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO i think we can close this issue if the raised in the ticket is fixed and open a new one for this new issue.

**Comment by FanFanDAO** [comment]
@oluwatunmiisheii the little misalignment is part of matching the layout Adenuga.

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO you might need to do a hard reload

https://sweet-caramel-git-fix-staking-loading-spinner-popcorn-dao.vercel.app/ethereum/staking/0x27a9b8065af3a678cd121a435bea9253c53ab428

**Comment by FanFanDAO** [comment]
@anthonymartin, the above preview link looks good to me. If this is good, we can merge and bring it live.

**Comment by anthonymartin** [comment]
looks good to merge once CI is fixed https://github.com/popcorndao/sweet-caramel/pull/1394
