### ISSUE TITLE
Analytic Tracking Prompt (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1356]
## Description
We need a minimalistic design to convey either opt-in or opt-out of the analytic tracking (We use Google Analytics).  This design integrates into the Dapp and Mainsite. This should not spend too much time but do quick research always.

- popcorn.network
- popcorndao.finance

**Stakeholder opinion:**
- not a popover but a bottom screen slide-up menu minimum looking
​
## Specific Acceptance Criteria
- Research the best practices and provide reference images before you start
- Design 3 unique versions (Desktop & Mobile)
- Present all applicable states: hover, on-clicked, dropdown
- Provide JPG images per version. (Attach doc by commenting on this ticket. Once done, please move the ticket to the Review column and assign the PM.)
- (Optional) Create a Loom video, Figma prototype, and/or PDF explainer if necessary (Attach doc by commenting on this ticket.)
​
## Resources
Ask the PM 

## General Development Requirements
- Structured display and organization for all design-related files (e.g., Figma, Miro Board, etc.)
- Logical file, screen, and layer naming systems
- Always design in auto-layout / smart components
- Update and link components in the design system when a new system is created

**Comment by jakebraimah** [comment]
Mainsite (popcorn.network):

 - Desktop 


![Analytics modal.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/71dfa7c5-955d-46e6-bd35-d75934ea4778)


![Analytics slider.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/c96c0da4-1c32-4eb1-a64e-b866f3bc18de)



![Analytics slider-1.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/9e3e1784-1a78-4a17-9c09-0148119b0962)


  - Mobile

![Analytics.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/e0471139-e49a-4fcf-8538-07a6c78b4af2)

![Analytics-1.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/8011510f-df47-49c1-a2af-86c6ddd063c7)![Analytics-2.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/382197a8-3074-45aa-a8de-eb9f1f6b390b)


Dapp (popcorndao.finance):

  - Desktop

![Analytics_Modal.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/a9a15d4e-6f72-4b6b-abca-c5cc01d7979c) 




![Analytics_Slider.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/6916cbe1-5d84-408b-82e9-766ddeb31aec)



![Analytics_Slider-1.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/323d2048-bde1-4f64-84a1-b448edbc9c71)



 - Mobile


![Application_Analytics_mMdal.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/755b265b-ea0d-4a4c-a109-0e749445e426)



![Application_Analytics_Slider.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/22ef5064-35d9-4810-80ff-1df61dd0d887)


![Application_Analytics_Slider-1.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/37ca262f-3cb9-42a3-9e2a-ffba2046d29b)

**Comment by FanFanDAO** [comment]
@jakebraimah Hi Jake, they are popover. 
The ticket says we are not going for popover as we have too many at the moment, which can be a disturbing user experience. However, we had agreed on a design for the bottom slide-up menu. Please read the ticket carefully so you don't miss the critical info under Stakeholder opinion and Specific Acceptance Criteria.

**Comment by jakebraimah** [comment]
Mainsite:

![Analytics slider-2.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/b3315a5e-dd87-4f15-95ff-d0b94c32712f)


![Analytics slider-1.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/7b67c11f-e17a-4ece-9beb-7ddb1ce01f18)



![Analytics slider.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/045767f1-2e3c-44b9-98a5-85bd0fd919fa)


![Analytics-1.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/12207a07-01fb-4df9-a7d8-5fed87db4ea0)



![Analytics.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/bc76a537-fe3a-46b4-a2f4-97a2dcc77753)

**Comment by jakebraimah** [comment]
Mainsite:

![Analytics slider-2.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/b3315a5e-dd87-4f15-95ff-d0b94c32712f)


![Analytics slider-1.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/7b67c11f-e17a-4ece-9beb-7ddb1ce01f18)



![Analytics slider.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/045767f1-2e3c-44b9-98a5-85bd0fd919fa)


![Analytics-1.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/12207a07-01fb-4df9-a7d8-5fed87db4ea0)



![Analytics.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/bc76a537-fe3a-46b4-a2f4-97a2dcc77753)

**Comment by jakebraimah** [comment]
Dapp:

![Analytics_Slider-2.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/384c1f05-35a7-43e7-84cb-75a65b15eca1)



![Analytics_Slider-1.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/d69bc16b-6460-4a76-a2c8-6c39474ccad4)



![Analytics_Slider.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/6e6482d5-dd30-41be-b8b1-e748d848ac50)



![Application_Analytics_Slider-1.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/45f0bfda-f138-403f-86d1-104b3adbfc06)


![Application_Analytics_Slider.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/8a13581d-945d-435e-850d-90bec36f7997)

**Comment by FanFanDAO** [comment]
@jakebraimah it still looks like a popover though for desktop. 

@anthonymartin what do you think? The last images are attached above by Jake.

**Comment by anthonymartin** [comment]
they look nice - but are a bit big. can we make them  about 75% smaller and less intrusive?

**Comment by jakebraimah** [comment]
@anthonymartin @FanFanDAO 

I reduced the sizes, not too much so they won't look similar to 'popovers' and also removed the 'cancel button' , to ensure users pick one option (if the cancel button is present, you'll find that alot of user activity data won't be recorded). I also reduced the shadows on the mobile view to make them less intrusive (i left the shadows for desktop to ensure the design doesn't disappear into the background).

Mainsite:


![Analytics slider.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/3aa5d106-9900-44c2-b627-cc1046f46eee)![Analytics slider-1.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/baf08564-0a00-48eb-8921-9adb0e6de6fa)

![Analytics.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/95a0f24b-7f07-4198-9a0a-5b6bcdf65556)



![Analytics-1.jpg](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/a37fbd21-e3ee-401d-847f-15cca8b52e66)



Dapp:


![Analytics_Slider-1.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/01e2d8f2-39ea-45ec-acf6-8790b24ed7fb)![Analytics_Slider.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/a53f054a-c409-4cb9-8445-fb71a4f885fe)






![Application_Analytics_Slider.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/7538fe56-200d-4948-819e-0215b6ec5463)



![Application_Analytics_Slider-1.png](https://images.zenhubusercontent.com/635bf68bfccdb9647ab9e6ec/afa08ce5-da87-40d5-92b0-1d3466bd84ac)

**Comment by FanFanDAO** [comment]
@jakebraimah @anthonymartin I have just spoken to Anthony, and this is not good enough. Can you look into it more on the best practices for showing this and provide the design as soon as possible? 

Feedback:
- majorly reduce the size
- it is very distracting with the size currently
- I don't think we need to express that we use Google analytic in such a big header copy
- can you show me some references you found, for example, how other websites do it and without being distracting?

**Comment by anthonymartin** [comment]
whoops - I accidentally deleted fan's feedback when I wanted to edit for context. here it is:

> [@jakebraimah](https://github.com/jakebraimah) [@anthonymartin](https://github.com/anthonymartin) I have just spoken to Anthony, and this is not good enough. Can you look into it more on the best practices for showing this and provide the design as soon as possible?

Feedback:

majorly reduce the size (it looks like it was only reduced 25% percent - but should be reduced more like 75%)
it is very distracting with the size currently
I don't think we need to express that we use Google analytic in such a big header copy
can you show me some references you found, for example, how other websites do it and without being distracting?

**Comment by FanFanDAO** [comment]
@anthonymartin @jakebraimah Hi Anthony, Jake has worked on this final output, and we communicated on the design before posting the above. Based on the relevant reference examples (references attached above) we have found, we both think this design will work well for desktop and mobile. Please let us know if this is good to know or if you have any additional feedback, kindly let us know.

**Comment by anthonymartin** [comment]
lgtm
