### ISSUE TITLE
05 - Copies for Sweet Vault

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1361]
## Description
To prep for Sweet Vault's upcoming launch, it is important that we focus on the copies that we want to communicate in the subheadline and the carousel component inside each vault. Please check the reference image below. 

As I had looked into the origin of the vaults and Yearn seems to have all the copies, I think we should ideally rework it with a bit of Pop branding instead of a copy-and-paste mentality. As I am not a primary English speaker, I think the best person to work on the copy should come from Marketing. 

Additionally, if we need more sections and copies in our carousel that would help us to convert, they are all welcome.

Vaults:
https://yearn.finance/#/vault/0x986b4AFF588a109c09B50A03f42E4110E29D353F
https://yearn.finance/#/vault/0x3B27F92C0e212C671EA351827EDF93DB27cc0c65
https://yearn.finance/#/vault/0xE537B5cc158EB71037D4125BDD7538421981E6AA
​
## Specific Acceptance Criteria
- Provide all the copies needed per vault
- Provide or confirm copy of the subheadline

## General Development Requirements
- Please comment within this ticket under the comment section below in a structured manner when done

## Image References
![Sweet vaults_USDT_Deposit_D.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/dd5a7c7c-dbfb-4ef8-90da-848a83f6afee)

**Comment by FanFanDAO** [comment]
@sirkisselgof can you attach the doc here or sent it to me?

**Comment by sirkisselgof** [comment]
I put the descriptions on notion:

https://www.notion.so/popcorn-network/Sweet-Vault-Options-Copy-3d5f34bc4ae246eea425bf29d7390346
