### ISSUE TITLE
Port KeeperIncentive Test into foundry

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1369]
Recreate the test scenarios from KeeperIncentiveV2.test.ts and KeeperInencitvized.test.ts in foundry tests.

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1405

Theres one failing test that I am struggling to understand

test__shouldDeductIncentiveRewardFromIncentiveBalance

**Comment by Amirjab21** [comment]
This has already been brought into the main branch - so this should be closed @RedVeil
