### ISSUE TITLE
Setup Storybook

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#1380]

**Comment by oluwatunmiisheii** [comment]
@RedVeil 
https://github.com/popcorndao/sweet-caramel/pull/1387

**Comment by RedVeil** [comment]
@oluwatunmiisheii I tried running `build-storybook` and `storybook` but while the build worked. launching storybook didnt. Some Websocket issue. Could you check that out? or let me know how you could launch storybook.

**Comment by oluwatunmiisheii** [comment]
@RedVeil 
From the UI directory, run yarn add ws@latest
Then run yarn storybook

**Comment by oluwatunmiisheii** [comment]
@RedVeil 
From the UI directory, run yarn add ws@latest
Then run yarn storybook
