### ISSUE TITLE
Update form in our design system and all related files

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1403]
## Description
We have finalized and updated the new system for our forms after working on the Sweet Vaults design, and the new system needs to be updated cross.
​
## Specific Acceptance Criteria
- Replace the arrow icon next to the token name with a swap icon
- Update the new wallet amount display and make sure you understand how it function
- Update and adjust all current existing forms (Mint form, Stake form) to follow the same rules (Desktop & Mobile)
- Update the Design System on each folder (Desktop & Mobile)
- Update each screen on each folder
​
## Resources
Ask the PM 

## General Development Requirements
- Work from a test page and only bring approved and finalized designs into the Desktop or Moble pages in a Figma folder
- Structured display and organization for all design-related files (e.g. Figma, Miro Board; etc)
- Logical file, screen, and layer naming systems
- Always design in auto-layout / smart components
- Update and link components in the design system when a new system is created

## Image References
![Screen Shot 2022-11-08 at 2.38.04 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d3769690-5990-4964-ad65-513f543d2157)
![Screen Shot 2022-11-08 at 2.38.14 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1c04a778-6d24-43e0-9d35-bb601c9f29e7)

**Comment by JustinaPop** [comment]
Currency swap icon updated across the design system.
 I found some inconsistency issues on the 3X minting form  -  
1) New currency Swap icon color (off Gray 400) and 3X icon (off Gray 300)
2) All tool tip icons are different styles and colors
![Screen Shot 2022-11-24 at 10.47.34.png](https://images.zenhubusercontent.com/637dfb39161d96e44eccf5cb/bd96d37d-e971-4c5f-81d6-eca5c8d4e6d5)

**Comment by FanFanDAO** [comment]
@JustinaPop 
The latest form adjustment is on Sweet Vault. The form reference images are attached above. Please follow the color or suggest a color if you think it is necessary for this class element based on our design system.

For the info tooltip icon, please follow the one observed on Sweet Vault screens.

**Comment by JustinaPop** [comment]
Design system updated
