### ISSUE TITLE
Google Analytic Prompt (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1412]
## Description
This analytic prompt gives us the right to understand our users and traffics better. Please implement this and ask the related person who has ownership of the Analytic account access if needed.
​
## Specific Acceptance Criteria
- Fetch data and data logic
- (For the Dapp): should be done in feat/greenfield-packages in packages/greenfield
- Make sure all states are covered if applicable (e.g. hover, on-clicked; etc)
- Have preview link(s) ready and attach them to the comment under this ticket for review
- Layout (Desktop & Mobile)
- All related functions (Desktop & Mobile)
​
## Resources
Ask Jake (Our designer)

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-11-11 at 12.58.00 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d4b5d1b3-c5f9-4a07-8ad8-08fc06cd0e70)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://sweet-caramel-e05ng09qp-popcorn-dao.vercel.app/  - for .finance
https://new.popcorn.network/ - for .network

**Comment by FanFanDAO** [comment]
@Ajiva-D Can we ensure the round corners are consistent with other existing modals of the same class for mobile?
![Screen Shot 2022-11-21 at 11.34.43 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d34d0dd0-8480-4547-9f30-a9424abbeb5c)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://beta.popcorndao.finance/
