### ISSUE TITLE
upgrade grants package in `main`

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#1414]
It was necessary to remove `packages/grants` from main temporarily because `packages/greenfield-app` was somehow using next dependencies from `packages/grants` which were causing builds to fail. We need to merge `packages/grants` back into main and update the next dependencies so it uses the same ones used by `packages/greenfield-app`.

Acceptance criteria:
1. running `yarn next build` works correctly in `packages/greenfield-app` and `packages/grants`
2. running the build above will not produce a message in either package about using `webpack 4`
3. next should be upgraded to the same version on `packages/grants` as `packages/greenfield-app`

**Comment by Amirjab21** [comment]
pr:

https://github.com/popcorndao/sweet-caramel/pull/1422

I wasn't getting any error about webpack 4 so I'm not sure if this fixes it or not but I'm pretty sure the current Next version uses webpack5.
