### ISSUE TITLE
Update token icons with network stickers to all product detail page (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1425]
## Description
We have integrated the network filter into our Dapp on the multi-products display pages. Now, we should update all product detail pages with token icons that have the network stickers, so it makes it clear to users which contract they are interacting with at all times.
​
## Specific Acceptance Criteria

- nextJS images (faster load)
- Fetch data and establish data logic
- should be done in feat/greenfield-packages in packages/greenfield
- Layout (Desktop & Mobile)
- All related functions (Desktop & Mobile)
- Have preview link(s) ready and attach them to the comment under this ticket for review

## Resources
Ask the PM.

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-11-17 at 2.41.11 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8a399ebe-d76c-4f26-9e8d-f7f3dd2f5444)
![Screen Shot 2022-11-17 at 2.46.35 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/714537ec-24a1-41a5-b114-ec08270dca79)

**Comment by oluwatunmiisheii** [comment]
Here is the preview link @FanFanDAO 

https://sweet-caramel-j9d9pmh6l-popcorn-dao.vercel.app/staking

**Comment by FanFanDAO** [comment]
@RedVeil Looks good to me. Can you code-check and bring it to live?
