### ISSUE TITLE
Update info tooltip icon size to 16x16px globally (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1426]
## Description
We the new design for the Sweet Vault Deposit & Withdraw form, we readjusted the info tooltip icon from 22x22px to 16x16px. Anthony felt that the icon was too big and that we should make it smaller during our live design session.
​
## Specific Acceptance Criteria
- update the size of the icon globally
- spacing between the header to the icon is 8px
- nextJS images (faster load)
- Fetch data and establish data logic
- should be done in feat/greenfield-packages in packages/greenfield
- Layout (Desktop & Mobile)
- All related functions should not be affected (Desktop & Mobile)
- Have preview link(s) ready and attach them to the comment under this ticket for review

## Resources
![icon_tooltip.svg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1319ecc9-ef96-446c-b8ee-b87b84e15cd9)

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-11-17 at 2.52.44 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ffa67a18-c810-410a-b7c0-200d4c7177f3)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://sweet-caramel-e05ng09qp-popcorn-dao.vercel.app/

**Comment by FanFanDAO** [comment]
@Ajiva-D ! Hi David, I saw a misalignment happening here. can you double-check?
![Screen Shot 2022-11-21 at 11.31.09 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a3d6394f-2c2b-4282-9640-044b4841b38c)
