### ISSUE TITLE
Loading for the feature data states on 3X page should always be in one line (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1430]
## Description
The loading of the feature data states went into a two-liner on the 3X page. It should always be in one line with the same spacing between one data point to another. 
![Screen Shot 2022-11-18 at 10.48.46 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c32c4e53-ef36-4334-b6f5-31409868ff94)
​
## Specific Acceptance Criteria
- Fix the desktop data layout to be in one line with the same spacing between one data point to another, just like the loaded look
- Should be done in feat/greenfield-packages in packages/greenfield

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

**Comment by Ajiva-D** [comment]
https://sweet-caramel-e05ng09qp-popcorn-dao.vercel.app/ethereum/set/3x @FanFanDAO
