### ISSUE TITLE
github workflow: run prettier formatting for all commits

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#1434]
A github workflow should be executed which will run `yarn prettier` for all pushes to all branches. It should run the formatter and  commit the formatting changes if any need to be applied. This will reduce the occurrences of merge conflicts and create uniformity in the code base style

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1455

**Comment by Amirjab21** [comment]
Updated PR: https://github.com/popcorndao/sweet-caramel/pull/1476

This modifies the commit on github to include Prettier

Which means that you'll have to fetch from origin if you push something which gets prettified on the CI.

It's a minor inconvenience but it shouldn't occur unless you've turned prettier off on your machine.
