### ISSUE TITLE
create storybook layout using greenfield-app layout / css

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#1436]
## Background

In order to start writing components in storybook, we need to bring in the styles from greenfield into a layout that are used to render components. 

## Acceptance criteria

* a modal component will be rendered with the styles from app / greenfield - it will be rendered insde a layout from the react project

**Comment by Ajiva-D** [comment]
@RedVeil this can be tested by running the react app in packages/components. There is a button that has our styles and it will trigger the modal with our tailwind styles too.

**Comment by RedVeil** [comment]
@Ajiva-D The component is fine but currently in next. Use the button examples in storybook to move the component into storybook. Than it will be good to go
