### ISSUE TITLE
(Mix misalignment for the tooltip icon on all staking detail page (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1449]
![a3d6394f-2c2b-4282-9640-044b4841b38c.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/22f0f1eb-a140-4408-9cb9-01d8e6ce5026)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://beta.popcorndao.finance/
