### ISSUE TITLE
Bug: The network switcher pop up menu should be fully visible on viewable screen areas on a browser (Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1474]
## Description
From the user "when changing network via mobile (iOS 15.6.1) the pop-up doesn’t extend up high enough to show the network options" Reference image is attached below.
​
## Specific Acceptance Criteria
- Address the issue mentioned above (Mobile)
- Double-check on Safari, Brave, and Metamask browsers by providing screenshots (Mobile)
- Should be done in feat/greenfield-packages in packages/greenfield
- Dapp: Have the preview ready on https://beta.popcorndao.finance/ 

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![IMG_1684.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/91b3ba1e-f973-41f3-b951-ec9d9d99d983)

**Comment by oluwatunmiisheii** [comment]
@fan https://beta.popcorndao.finance/
