### ISSUE TITLE
claiming stablecoins from redeem batch shows wrong modal

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#250]
after claiming stablecoins from a redeem batch, the wrong modal was shown:
![Screen Shot 2022-01-18 at 3.25.56 AM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/22c95d93-3811-40e8-99fc-af39db272f33)

Also, the modal was displayed before the transaction was confirmed. For mint batches, when they are claimed, the modal should only be displayed after the transaction is confirmed

**Comment by FanFanDAO** [comment]
@thenerdcat Can you revert this text as Anthony mentioned above?
@mishraashish006 We need to revert the copy. 

Sorry about this. Let's find ways to better communicate on copies moving forward. Love love.

**Comment by mishraashish006** [comment]
![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/2387e5a2-3f8f-4aff-98d0-7fbcb296cb70)


Reverted

**Comment by thenerdcat** [comment]
seems good to me

**Comment by FanFanDAO** [comment]
@anthonymartin text reverted based on your request. From the screenshot, it looks good to me. :)
