### ISSUE TITLE
Landing Page Adjustment - Introducing Forex and Sweet Pools (Waiting for illustration)(Block by re-branding as well)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#276]
## Context
Leon: Butter is a basket of two decentralized dollar-based stablecoins. Forex butter will be a basked of non-usd stablecoins. so what is attractive to users one over the other? Ans: It uses non-USD stable coins so you can diversify without relying on the dollar.

## Source File
- Figma > Butter Page

## Key Design Requirements
- Let's try to see how we can incorporate simple illustrations here
- On brand and aligned with our Design System 1.0
- UX and its entire flow should be catered to both mobile and desktop at all widths and sizes
- Make sure you are thinking hover state, on-press state, and inactive state at all times when applicable

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-01-19 at 10.48.59 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/48619e73-b174-46a0-b391-7ff965d8daf4)

**Comment by FanFanDAO** [comment]
@anthonymartin we are reworking the illustration. I will keep you posted.

**Comment by FanFanDAO** [comment]
@anthonymartin Here's the mock with the updated illustrations for our latest landing page. The subline for 4X is yet to be written. :)
![26042022.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/87d53350-7cd3-43c4-9d91-c3dcdce4f2d5)

**Comment by FanFanDAO** [comment]
@anthonymartin Here's the mock with the updated illustrations for our latest landing page. The subline for 4X is yet to be written. :)
![26042022.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/87d53350-7cd3-43c4-9d91-c3dcdce4f2d5)

**Comment by anthonymartin** [comment]
can you make the butter image a bit more understated? it's seems out of proportion

**Comment by annisharafi** [comment]
@anthonymartin updated, wdyt?
![Screen Shot 2022-05-09 at 23.02.33.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/d3a995f2-a779-4486-94f5-c39e4e3efd56)

**Comment by FanFanDAO** [comment]
@annisharafi  I think the 4x icons should have a stroke so the style of illustration is consistent. You can make those icons simpler without the white ring.
For butter, it is too small. We need to make the icons the same size as 4X icons and different arrangements.

**Comment by annisharafi** [comment]
updated fan
![Screen Shot 2022-05-11 at 00.10.55.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/aa6032b9-8974-4c77-8635-146eb4c70200)

**Comment by FanFanDAO** [comment]
@annisharafi where did you get the color you used on the Butter token illustration? They seem to be new color outside of our secondary color...

**Comment by annisharafi** [comment]
for butter color I use color from the original logo of the token. here's an update. wdyt @FanFanDAO ?

![Screen Shot 2022-05-14 at 00.25.54.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/e501246a-b19c-45f3-a597-39f71d97e229)

**Comment by FanFanDAO** [comment]
@anthonymartin Just need you to confirm the latest illustration we did in-house and get the one-liner copy ready for the 4x yellow card.
