### ISSUE TITLE
Tooltip for Vesting Record (needs copy)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#329]
## Copy Focuses
We should explain what is a vesting record and how it is generated.

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same as our Figma original design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Image Reference
![Screen Shot 2022-01-21 at 6.17.08 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/60642e93-a6ea-4534-b17f-fe8c43549995)

**Comment by anthonymartin** [comment]
Copy to use:

"Every time rewards are claimed, part of the earned rewards are streamed over time. Each new record below allows you to claim newly unlocked rewards. You can come back to this page periodically to claim new rewards as they are unlocked."

**Comment by FanFanDAO** [comment]
@anthonymartin The vesting record and tooltip function was previously done by Fernando under this ticket: https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/287
