### ISSUE TITLE
Make "How it works?"-Carousel on Mobile swipeable

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#334]
## Source File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2253%3A29429

## Key Development Requirements
- Animations required: (1) When the user clicked on the tab, the panel should slide in from the right to the left with a fade-in effect as well. (2) When the user clicked on the "arrow" icon, it should slide our from left to right with a fade-out effect. 
- Add back arrow button on mobile
- Dots indication feature to show which image are we at. (A clarification facilitator)
- Mobile view starts at 768px (Agreed by Arne)
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same value in our Figma original design. (Check the Inspect panel for info)
- This page and the entire UX flow should be adaptive with fluid transition across all mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-01-24 at 6.09.52 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ac48c91c-a9de-471f-90d3-75566ea4458d)

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/559
