### ISSUE TITLE
Show extra details in withdraw interface for POP staking

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#408]
Currently in the staking/withdraw screen for POP,  the following details should be shown:
unlock date, time remaining, amount locked

![Screen Shot 2022-02-04 at 8.30.05 AM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/7f534c1e-034b-474e-ae15-56e66f73816d)

## Current design reference
![Screen Shot 2022-02-04 at 9.00.47 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/958fb4b5-28ef-4667-8221-35a63693862e)

**Comment by Amirjab21** [comment]
@anthonymartin What do we do if they have staked on 2 occasions with differing amounts and differing lock periods? Do we just show the most recent one OR provide a drop down?

**Comment by anthonymartin** [comment]
@FanFanDAO what do you think about @Amirjab21 's question

**Comment by FanFanDAO** [comment]
@anthonymartin @Amirjab21  Good catch Amir! Thank you :)
Here is the design update. Let me know what you guys think:
![Screen Shot 2022-03-18 at 11.18.45 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8457c9ef-ea58-4eaf-aef1-664b1bc0d7c2)

**Comment by Amirjab21** [comment]
@FanFanDAO How should the dropdown look? Should I base it off of an existing component or make a new one?

**Comment by FanFanDAO** [comment]
@Amirjab21 Yes, we can have the dropdown with a max height showing four records at a time. Inside the dropdown, there should be a gray scrollable indicator bar.

![Screen-Shot-2022-03-21-at-10.30.58-AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2b04e08c-4f63-4bb2-870d-306dc20eee42)

**Comment by Amirjab21** [comment]
@anthonymartin @FanFanDAO Should this be only for POP staking or all staking interfaces?

**Comment by anthonymartin** [comment]
@Amirjab21 it's only applicable to POP staking

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/560

**Comment by Amirjab21** [comment]
Here are the screenshots as we can't view it on any of the real networks. @FanFanDAO 

P.S it seems that if you stake twice in one day, it just counts it as one vesting record.

![Screenshot 2022-03-23 at 11.29.24.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/1b3bd912-b75f-4116-bec5-20a5558270c2)![Screenshot 2022-03-23 at 11.25.43.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/16696b45-d573-4ce4-9b47-32acedf96d7b)![Screenshot 2022-03-23 at 11.25.37.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/5449705c-af43-42ab-8e0f-445b7359037c)![Screenshot 2022-03-23 at 11.25.33.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/142bdd0b-1873-4834-a8be-44aeddf6ffbe)

**Comment by FanFanDAO** [comment]
@Amirjab21 Feedback:
![Screen-Shot-2022-03-24-at-3.34.48-PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/52a886be-d4eb-4a91-8c01-077758fd6467)

**Comment by Amirjab21** [comment]
@FanFanDAO Do you mean just the vertical spacing?

**Comment by FanFanDAO** [comment]
@Amirjab21 I mean the left and right alignments and spacing. The red guides show you think that needs to be aligned. I provided a screenshot of your design vs our Figma design.

**Comment by FanFanDAO** [comment]
@Amirjab21 can you attach a screen capture just like before? :)

**Comment by FanFanDAO** [comment]
@amirjab21, we just need to ensure that “Amount  0POP” is aligned with text ”April 1st, 2022” and that the spacings between the three data sets are consistent and equal. 

@annisha Amir has provided an image references on a narrow state where “remaining” goes under “Amount & Unlock Date”. This scenario makes sense. However, we need to make sure that it looks balance. Maybe the box for “Remaining” need to auto fill to full width. Can you mock up this state and send me the design so that I can check and Amir can implement? Xox

**Comment by annisharafi** [comment]
here's the update @FanFanDAO 
![Screen Shot 2022-04-05 at 22.53.18.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/389d31e1-a9d7-43f0-a48e-d97313c123f8)

**Comment by Amirjab21** [comment]
![Screenshot 2022-04-08 at 12.19.28.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/dc61df09-91cc-4890-a5e2-e7513624fe8b)

![Screenshot 2022-04-08 at 12.18.58.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/bbf20dad-c3dd-4d47-91ac-6c71a710bb0e)
