### ISSUE TITLE
add reverse lookup to contract registry

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#433]
Currently, no reverse mapping exists whereby a client can ask the contract registry if an address exists in the the registry. In order to validate certain contracts against the registry, it would be useful to maintain a mapping when contracts are added and removed from the registry.

**Comment by anthonymartin** [comment]
> Should expose reverse lookup functions in the ContractRegistryAccess class too.
@bhanusanghi can you do this please?

Also, note that versions aren't really used. @RedVeil had questioned their necessity for the original implementation and I thought it would be useful to include, but it's actually more burdensome. Version is a bytes32 and it's quite difficult to know & get the value from client contracts. We might want to remove it. 

> Makes sense to return the contract name and version from this function (i.e., forward lookups take (bytes32 name, bytes32 version) and return address, this should take address and return (bytes32 name, bytes32 version))
Which function are you referring to @ecmendenhall ? `getContractFromAddress`?

**Comment by bhanusanghi** [comment]
Have addressed these comments and made a push

**Comment by leomarlo** [comment]
@ecmendenhall  what is the task for this issue. Bhanu is working on this, no?
