### ISSUE TITLE
display modal / button if wrong network is active

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#475]
* If chainId from the wallet does not match the chain id from the app, then a button to switch wallet to the currently selected network should be displayed next to the network switcher. Additionally a modal should appear to direct the user to switch the wallet network.

## Image reference

![Screen Shot 2022-02-22 at 5.02.32 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/12c46634-55b2-4b95-8bc4-9c38c4423f92)

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/658
