### ISSUE TITLE
Research onboard implementation instead of web3modal

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#528]
From Amirs research we learned that web3modal is not well maintained which is why i looked for other connect options.

One that stood out was https://www.blocknative.com/onboard. Which is used by yearn, curve and a bunch of others.

I think we should research how much effort it would be to use this for all our connections and what that would mean in terms of network switching

**Comment by Amirjab21** [comment]
This would completely replace web3react and web3modal and the package is well maintained. It's also much better designed and switching networks uses the same method for all different wallets.

I'm going to go ahead and create a new ticket for bringing this in.
