### ISSUE TITLE
implement web3modal [sweet-caramel]

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#529]

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/522

**Comment by FanFanDAO** [comment]
@Amirjab21 Nice. I like the mobile animated transition on the modal as well. :)
@anthonymartin I guess other wallets mentioned above are not ready, but the frontend is good to go in this case.

**Comment by FanFanDAO** [comment]
@Amirjab21 Just a little note. Please do remember to move the ticket to the Review column when you provided the PR for review. Love love...
