### ISSUE TITLE
Mobile loader

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#531]
## To-do
We have created loaders for the desktop site and we need to readjust for mobile.
The two loaders we need are modal loaders and the whole-page loader which is a popcorn icon. Please check this desktop loader reference on develop.popcorndao.finance

## Check
Please check this desktop loader reference on develop.popcorndao.finance

## Image Reference
Currently, on mobile, the modal loaders are all wrong and not aligned. There left and right padding should be 24px.
![257a577f-021d-4af2-a983-71ebb7cd781d.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/059f2b1c-aba8-4406-8d5d-a63336e5dbe8)

**Comment by mishraashish006** [comment]
@FanFanDAO FYI

**Comment by FanFanDAO** [comment]
@anthonymartin @thenerdcat The design has been updated above. As previously discussed with Fernando, the module loaders will adjust so that it follows the size and layout of the modules per page.

**Comment by anthonymartin** [comment]
@FanFanDAO could you create the ticket for implementing the new design?

**Comment by FanFanDAO** [comment]
@anthonymartin Ticket created: https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/556
