### ISSUE TITLE
import workspace frontend app into sweet-caramel repository

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#538]
## Background

We have a beneficiary governance / grant frontend in the workspace repository that we would like to import into the sweet caramel repository. It is in `packages/app` directory on the `develop` branch. 

In order to successfully import the frontend, we must copy over the `packages/app` directory into `packages/grants` and ensure the frontend loads correctly with references to the correct contracts from the `hardhat` directory. Additionally, it might be necessary to update the `packages/utils` directory to include any files that may have not been previously imported or removed. 

## Success Criteria

* The grants frontend should work including:
  * submitting applications to IPFS and blockchain
  * voting for beneficiary grants

* References to contract addresses  as environment variables should be replaced by contract addresses in hardhat directory
* No build errors

**Comment by Amirjab21** [comment]
@anthonymartin so the grants folder will be a separate nextjs app on Sweet Caramel

**Comment by anthonymartin** [comment]
@Amirjab21 yes that's right

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/549

This will be a smaller PR once Arnes changes are merged into develop.
