### ISSUE TITLE
Propose new Issue Template for UI Issues

### ISSUE THREAD

**Issue by arne-z** [popcorndao/sweet-caramel#555]
_The following is an example for the new ticket layout based on the contents of ticket https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/31_

## Description
_A general description of what this ticket is about._
We are coding the layout and form fields of the Beneficiary Application flow for Step 4. The drag and drop function should be made possible here. Please pay attention to the reference images below where it shows you the different states during the image upload process. The top nav and the footer will be coming from different tickets therefore this ticket has two dependencies.
​
## Specific Acceptance Criteria
_A list of specific requirements unique to this ticket. These can be understood as a type of checklist for the developer to make sure everything was considered. During backlog grooming & estimating we should aim to add additional detail here._
- Drag and drop image functions should be made possible
- Next button should be inactive until the user uploaded at least one image.
- One Progress bar per file that is being uploaded in a list view
​
## Resources
_This should have a Link to the specific element in Figma, or any other resources that should be referenced (e,g, guides, libraries if applicable)_
https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

### General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Image References
_One or multiple images if applicable_
![Screen Shot 2022-02-10 at 9.41.21 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/45385a50-de1c-4dd1-926e-665b382f8225)
![Screen Shot 2022-02-10 at 9.41.32 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e4ea708e-31ae-4b15-92b8-8fdad75ddaa8)

**Comment by arne-z** [comment]
@FanFanDAO Very interested in your thoughts on this, I've tried to keep it mostly based on how you currently write tickets, so it's not a difficult transition but split things out a bit for easier reading.

**Comment by FanFanDAO** [comment]
@arne-z Thanks for sharing
@RedVeil @anthonymartin We had discussed this during our Design Study call today and I think it is doable this way also if the engineering team agrees.

**Comment by RedVeil** [comment]
I like this template a lot! :)
