### ISSUE TITLE
Staking Modal on Staking Landing Page (Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#561]
## Specific Criteria
- Follow the new design layout where the stake button goes to the bottom of the card

## Source File
- https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=6750%3A28653

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-03-22 at 11.00.29 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/25dc49e5-48ce-4da5-9995-64ff04d282cc)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://deploy-preview-770--sweet-caramel.netlify.app/ethereum/staking
