### ISSUE TITLE
Connect Wallet on Mobile doesnt connect

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#583]

**Comment by RedVeil** [comment]
Reference: https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/584

**Comment by Amirjab21** [comment]
When I try to connect on mobile, it gives the following error (now in a modal for the user to see)

"no Ethereum browser extension detected, install metamask on desktop or visit from a dapp browser on mobile"

It seems to me that Metamask is only available on a dapp Browser for mobile, as the metamask mobile app doesn't automatically sync up with the Chrome app to provide the extension.

@RedVeil
