### ISSUE TITLE
Change text on the "Info Icon" popover

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#585]
## Description
We got a user request and are replacing a clearer copy for the info icon popover from within the Batch modal.  
​
## Specific Acceptance Criteria
- Copy is now written by Anthony under the comment section

## Resources
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=2253%3A29429

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-04-11 at 5.32.15 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/0117d03e-3c0b-400d-ac86-98d1b0fb7bab)

**Comment by anthonymartin** [comment]
The copy should read: "Mint and redeem requests are processed manually approximately every 48 hours or when a batch reaches 100k"
