### ISSUE TITLE
Add "Info Icon" and popover text to Social Impact data set under the Butter page

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#586]
## Description
We got a user request to add an info tooltip to the "Social Impact" data set so that the user knows better what this data is meant to display. Currently, it states "Coming soon," and it is not clear to the user what this is. We had the info icon on our Figma original design, so we need to just implement it on the frontend and add the ready-styled popover with the below copy.
​
## Specific Acceptance Criteria
- Add an info icon to the "Social Impact" data set on the Butter page
- Copy is not written by Anthony under the comment section

## Resources
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=2253%3A29429

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-04-11 at 6.00.53 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/7c879fce-7919-4bf4-a19a-0d505af837da)

**Comment by FanFanDAO** [comment]
@anthonymartin, can you help write up a copy based on the suggested copy for this popover? :)

**Comment by FanFanDAO** [comment]
@anthonymartin, can you help write up a copy based on the suggested copy for this popover? :)

**Comment by anthonymartin** [comment]
The copy should read: "Approximately one-third of all fees collected by Popcorn are donated to social impact and non-profit organizations."

**Comment by arne-z** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/784
