### ISSUE TITLE
Add an accept terms popover after clicking "Restake"

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#587]
## Description
We got a user noticing that the terms are missing under Restake POP. This is a great catch! Therefore, we should implement a popover to accept the terms when the user clicks on the "Retake POP" button.
​
## Specific Acceptance Criteria
- Implement the accept terms popover function (**Similar popovers have already been created in the past, so it doesn't need to be created from scratch.)

## Resources
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=2253%3A29429

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-04-11 at 6.17.53 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a16c0133-7b79-4beb-aa57-73d8db5fd6aa)

**Comment by Ajiva-D** [comment]
![Screenshot 2022-05-31 at 12.34.21.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/b36632e4-3974-4f31-af20-a4f545e5a7d8)
