### ISSUE TITLE
Reward page not aligned with top nav 

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#592]
## Description
Currently, on popcorndao.finance, the rewards page is not aligned with the top nav on the desktop views, just like other pages. 

## Specific Acceptance Criteria
- Expand and align the page with the top nav on desktop

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen-Shot-2022-04-12-at-10.58.44-AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f84ecaab-2496-47d9-95e1-716feb8a9c66)

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/642
