### ISSUE TITLE
Text overrun on the "How It Works" carousel 

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#593]
## Description
Currently, on popcorndao.finance, I saw that the "How It Works" carousel on the Butter page has a text overrun situation on the desktop view. There should be a decent amount of spatial separation between the longest copy and the edge of the yellow frame.

## Specific Acceptance Criteria
- Expand the yellow frame 40px down (padding 40px) so that there is a spatial separation and does not look like an error

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen-Shot-2022-04-12-at-11.07.56-AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/36136a51-6788-4ac0-8d1c-a88f77992efb)

**Comment by anthonymartin** [comment]
the original styling for this was perfect I think - https://alpha.popcorndao.finance/butter - can we bring that back?

**Comment by arne-z** [comment]
Hey @bhanusanghi, I'm working on clearing out a lot of the bug tickets that are flying around right now. Could we sync up on the status of this ticket?

**Comment by bhanusanghi** [comment]
Hey Arne this has been fixed

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/645
I would propose this solution.

**Comment by FanFanDAO** [comment]
@arne-z Let me know if I need to review it. may I know what exactly is the solution on PR #645.
