### ISSUE TITLE
Change "Total Staked" & "Total Deposits" to TVL and show USD values

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#596]
## Description
Based on our user feedback, the "Total Staked" & "Your Stake Balance" should both display USD dollar value as it is more familiar to the users. 
​
## Specific Acceptance Criteria
- Change data value on both "Total Staked" & "Your Stake Balance" to USD dollar values
- All Staking detail pages should reflect the same USD dollar values

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-04-13 at 10.07.42 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a3734874-7ac6-4a21-92c8-77d78f5e67d4)

**Comment by bhanusanghi** [comment]
https://github.com/popcorndao/sweet-caramel/pull/730 - PR
