### ISSUE TITLE
Instant Mint (New Function) - Butter Page

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#599]
## Description
We are introducing Instant Mint, so people with money don't have to bother with the Batch Mint system. It works when the user clicks on the Mint button, and it triggers a popover to choose Batch Mint or Instant Mint. 
​
## Specific Acceptance Criteria
- Implement the popover with two panels to choose from ( see image references)
- Please reference panel animations with our popcorndao.finance landing page 
- Desktop and mobile required
- Add ButterWhaleBatch to contract registry
- Implement instaMint/instaRedeem using ButterWhaleBatch

## Resources
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=2253%3A29429

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
Main Page
![Screen Shot 2022-04-13 at 5.04.04 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8cb8448f-928e-4e58-ad80-1390dfc09879)

Popover
![Screen Shot 2022-04-13 at 5.04.10 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/61b15018-4cb1-498c-94b4-7e17035d3e93)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/599?planning-poker) with ZenHub @arne-z @ecmendenhall @leomarlo @RedVeil

**Comment by RedVeil** [comment]
Add some more info to explain what batching or insta-minting does

**Comment by arne-z** [comment]
![image.png](https://images.zenhubusercontent.com/5c6e9b98b3d46374d6a0d6b3/4645ce79-9854-41a8-b4a7-6464d6a4770f)

**Comment by arne-z** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/722

**Comment by FanFanDAO** [comment]
@arne-z remember to move this to review. xox

**Comment by FanFanDAO** [comment]
@arne-z I couldn't preview the PR actually!
![Screen Shot 2022-05-17 at 12.23.20 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/5d076543-9dd2-4fe5-aec1-b697dd65e5bf)

**Comment by FanFanDAO** [comment]
@arne-z @anthonymartin Hi Arne, I had discussed with Anthony about this since the spacing looks weird. Also, the animation and position on the expanded Adjust Slippage modal also can be better placed. Below, you will see the reference for the new positioning, spacings, and treatment for presenting the slippage percentage. 

## Specific Acceptance Criteria
- The spacing should be accurate to the Figma design
- Slippage percentage is now presented in parenthesis next to the text button. "Adjust slippage (1%)"

## Resources
-  Link to the design file: https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=6750%3A28653

## Image References
![A.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9ac144d2-f6b6-40ef-8953-e91d641ca8a8)
![B.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9bdf341e-f3f5-4f12-9270-62f5b3ce6d8c)
