### ISSUE TITLE
SC - Copy proofreading & enhancement 

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#60]
## Areas where copies need to be proofread and enhanced
![Screen Shot 2021-12-09 at 5.57.55 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/102aefa0-a652-401a-9d06-fa81b863b6df)![Screen Shot 2021-12-09 at 5.57.49 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/38a18961-158f-40a7-bcd7-a6ee1b31a063)
![Screen Shot 2021-12-09 at 5.58.00 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/38d949df-d414-4155-9adc-fe02f569600b)
![Screen Shot 2021-12-09 at 5.58.17 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/0f744b58-ee78-4e11-bd78-5d0af2f9b2aa)
![Screen Shot 2021-12-09 at 5.58.41 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1ca5a65f-7762-4d2e-8df4-4ceecd23ddc1)
![Screen Shot 2021-12-09 at 5.59.25 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/144749c0-cfe8-436d-9070-a5abcceaf556)
![Screen Shot 2021-12-09 at 5.59.35 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c0313a7b-9466-422e-8751-3fd06f98a275)
![Screen Shot 2021-12-09 at 5.59.48 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ad3fa88e-3311-480a-843a-834a0b303340)
![Screen Shot 2021-12-09 at 6.00.03 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1a065a60-1c32-4dea-a9ce-a495610eca88)

## Source File
https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2253%3A29429

**Comment by anthonymartin** [comment]
newest copy is here: https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/78
