### ISSUE TITLE
Add "Platform" as a data set to all Staking cards

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#600]
## Description
We are including a data set "Platform" so that the user remains clear about the platform that is associated with the contract. 
​
## Specific Acceptance Criteria
- Make sure we add "Platform" data to each card. For example: "Platform: SUSHISWAP"
- Make sure both desktop and mobile views are updated and displayed like our Figma design
​
## Resources
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=6980%3A30532

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
Desktop view:
![78ca7f42-0288-451e-867a-524b4e984b07.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ded553d1-d8ab-4377-875f-13bc0da89b85)
Mobile view:
![78eae281-3759-4ad2-9577-9764c96549a3.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1ebb3e8b-682f-4641-949e-399cd36a9784)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/600?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @leomarlo @RedVeil
