### ISSUE TITLE
BTR Fee Converter

### ISSUE THREAD

**Issue by ecmendenhall** [popcorndao/sweet-caramel#602]
- Receive streaming fees in the form of BTR
- Use batched withdrawals to convert BTR to stablecoin
- Forward converted fees to the Rewards Manager

![Fee converters - BTR converter contract.png](https://images.zenhubusercontent.com/60ac1832916bb9d70bfff9c3/37f51b98-09ed-4991-8265-7b77bf407f21)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/602?planning-poker) with ZenHub @arne-z @bhanusanghi @ecmendenhall @leomarlo @RedVeil

**Comment by ecmendenhall** [comment]
BTR: Use batched withdrawals.
Yearn Vaults: Basically a zap out.

**Comment by anthonymartin** [comment]
I raised a draft PR to see the progress on this @bhanusanghi : https://github.com/popcorndao/sweet-caramel/pull/926

**Comment by RedVeil** [comment]
@ecmendenhall Left my review. Just some minor stuff
