### ISSUE TITLE
network switcher does not work on trust wallet

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#613]
Observed: When using the network switcher on trust wallet, nothing happens when selecting a new network. 

Expected: If the current browser does not support network switching from the dapp, then a modal should be displayed that says, "This feature is not supported by your browser. Please select a network directly within your browser to change networks."

**Comment by RedVeil** [comment]
This is not resolved. Onboard shows a modal which tells the user to change the network in their mobile app when connected via WalletConnect

**Comment by anthonymartin** [comment]
@RedVeil should we reopen this one? It's not related to walletconnect directly, but trust wallet itself
