### ISSUE TITLE
staking page: UI is jittery when amount is input

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#614]
Observed:  on mobile (iPhone & Android), when a staking amount is entered, i think the auto-refresh from SWR causes insufficient balance to show up when an amount is entered periodically because the data is reloading. The end result is that the page looks jittery because the insufficient balance text shows up quickly.

Expected: After enter a staking amount, the page should not refresh or feel jittery because of insufficient balance text showing up momentarily and sporadically.

**Comment by split-infinity** [comment]
Also having this issue on Windows, firefox - referenced here https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/639

**Comment by bhanusanghi** [comment]
Added a small time buffer of 1.5 seconds before we show/hide the error message. 
if a user stops typing only after 1.5 seconds does the UI update. This should get rid of the jittery feeling of instant message appearing/disappearning.

**Comment by anthonymartin** [comment]
I just saw this issue again on the butter staking page. Was this fix only applied to the POP staking page? @bhanusanghi @RedVeil
