### ISSUE TITLE
token icon is not added to metamask mobile wallet when adding POP token from UI

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#616]
Observed: when adding the POP token to wallet from metamask, the token is added, but the token icon is not.
Expected: when adding the POP token to wallet from metamask, the token and token icon should be added to metamask

**Comment by Amirjab21** [comment]
What environment was this on? Just tried this on production and localhost and it seems to be working as expected. @anthonymartin

**Comment by Amirjab21** [comment]
It looks this is a metamask issue:

https://github.com/MetaMask/metamask-mobile/issues/3722#issuecomment-1075063313

They've merged a PR that should fix the issue but I'm not too sure what we need to do here - do we have to update the metamask app or just wait?

@RedVeil

**Comment by Amirjab21** [comment]
![Screenshot 2022-05-09 at 11.26.21.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/d41ed8b3-c006-497e-b1d5-fc3be2d17e48)

Looks like we just have to wait.
