### ISSUE TITLE
Add POP to Wallet doesn't work on trust wallet

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#617]
Observed: When adding POP to trust wallet from the sweet caramel UI, nothing happens
Expected: If the browser does not support adding POP to wallet from the UI, a modal should appear to let the user know the instructions on how to add POP manually to the wallet. Alternatively, if trust wallet uses a separate API for adding a token to a user's wallet, then the sweet caramel should use that API instead.

**Comment by RedVeil** [comment]
Its not possible to do this with non-Injected wallets. Therefore we dont show this option when connected with smth else than injected wallets
