### ISSUE TITLE
Upgrade from web3react v6 to either v8 or a different library

### ISSUE THREAD

**Issue by arne-z** [popcorndao/sweet-caramel#625]
Web3react v6 is deprecated and suggests upgrading to v8. 
We should either do that or look for a more lightweight library as we only currently use web3react for RPC connections when we don't have a wallet connected. 
Any connections with wallets are handled by web3-onboard so we don't need web3react for that anymore.

**Comment by anthonymartin** [comment]
replace web3react with ethers wrapper for RPC-only connections

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/625?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @bhanusanghi @ecmendenhall @leomarlo @RedVeil
