### ISSUE TITLE
overlapping wallet visuals (desktop)

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/sweet-caramel#633]
What is expected:
Connecting wallet through metamask should provide a pop up that the wallet is connected, then disappear.

Description of what’s observed (what's actually happening):

![image.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/fc7f56d7-44c3-4b54-98ab-f152e1c8132c)
![image.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/ca65560f-758f-4bf0-b9e2-da8a36bad653)

Device, operating system, and where defect was found:

Windows, Firefox, Metamask

Steps to reproduce the bug:

Connect wallet to metamask. Occurs on every network.

**Comment by split-infinity** [comment]
also occurs when connecting with Wallet Connect 

![image.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/5a278c51-d390-4bc4-91ae-6ec89c1310bb)

Preview build 630

**Comment by arne-z** [comment]
@split-infinity  I've never seen this type of popup on the right of our page before, is this a chrome extension?
![image.png](https://images.zenhubusercontent.com/5c6e9b98b3d46374d6a0d6b3/68902b99-39af-468b-aceb-d794a0911a67)

This is what the navbar looks like on my machine:
![image.png](https://images.zenhubusercontent.com/5c6e9b98b3d46374d6a0d6b3/ec17a60f-b873-48a7-980e-2e01a5a1c90f)

**Comment by split-infinity** [comment]
@arne-z I don't have any extensions on Firefox except for Metamask. I'm testing it on Brave and getting the same issue (below). Wonder if it's a Windows thing? 

![image.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/21de30ce-2f31-4505-a4ad-f118bf92acf9)
