### ISSUE TITLE
loader does not show up on butter page

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/sweet-caramel#638]
expected: After connecting wallet, some kind of 'loading...' indication should appear if all elements cannot be displayed in a timely manner

observed: It can take up to ten seconds for the minting section to reappear after connecting wallet. this is enough time to cause user confusion and make them want to refresh the page

![image.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/52c7ef00-eb85-486e-93de-ae7cbe09b3f0)

System: windows, firefox, metamask or walletconnect - build preview 630

steps: connect wallet on butter page

**Comment by bhanusanghi** [comment]
https://github.com/popcorndao/sweet-caramel/pull/669

**Comment by bhanusanghi** [comment]
https://github.com/popcorndao/sweet-caramel/pull/669
