### ISSUE TITLE
Revise Sweet Vaults frontend

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#657]

**Comment by anthonymartin** [comment]
* create deployment script for sweet vaults
* create hooks for interacting with vaults

**Comment by Amirjab21** [comment]
four recent commits on this branch:
https://github.com/popcorndao/sweet-caramel/pull/524/

Theres only 1 commit that has actual changes - 2 are merges from develop and 1 is name change from sweet pools to sweet vaults.

**Comment by RedVeil** [comment]
TODO:
 - Add Addresses of the real yearn Vaults
 - Add Token descriptions of the real yearn Vaults
 - Add Strategy descriptions of the real yearn Vaults

**Comment by RedVeil** [comment]
Yearn Assets:
 - stEth / sEth
 - tBTC / WBTC
 - Curve cvxCRV
 - Curve 3Crypto

**Comment by RedVeil** [comment]
-- tBTC offers better yield but has a tiny market cap and has more price fluctuations than the underlying. It claims to have a great decentralized bridge but until there is more liquidity available it seems to risky.
-- sBTC is the synthetix BTC. technically a fine coin but it is pooled with renBTC and wBTC. renBTC and wBTC are both taking a much larger share in the pool. With all these depegs currently im not sure we should use this pool for 0.6% increased yield.
-- HBTC is provided by huobi which is a risk factor and the pool is very imbalanced.
