### ISSUE TITLE
4X Frontend

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#667]
We should create a frontend for 4X (A product similar to butter but based on ibToken). It will reuse the same page as butter and a similar contract but use some different tokens.

Jobs to be done
- Copy Butter Page
- Use FixedForexBatchContract instead of ButterBatch
   - All hooks should essentially look like the butter hooks but adapted for fixedForex
   - The apy calc should also resemble the useButterApy.tsx but filter for ffToken
   - The default inputToken is Dai and the default ouputToken is sUSD
   - Add the FFButterBatchZapper instead of the default ButterBatchZapper
- Add a new menu point in the products dropdown

**Comment by RedVeil** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/667?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @bhanusanghi @leomarlo

**Comment by FanFanDAO** [comment]
@RedVeil ![4x_icon.svg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9bbb9d32-4f0c-407d-8a8c-fecea80c5957)

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/726

**Comment by FanFanDAO** [comment]
@arne-z Good morning! The PR is linking me to Create Proposal Landing and not the 4X. Are you posting the above PR for frontend review?

![Screen Shot 2022-05-31 at 12.23.09 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9e6004af-d234-4f29-a7ae-8d69b2f54d2c)
