### ISSUE TITLE
About - Profile Detail Page with voting modal (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#679]
## Objective/Goal
We are coding the layout of the Profile Detail Page under the About tab. This version is with the voting modal and is for a beneficiary to become an eligible beneficiary. The voting modal, the top nav, and the footer will be coming from different tickets therefore this ticket has three dependencies. 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 10.18.49 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/485db046-177e-4ea4-a084-1ed8540fc6f6)

**Comment by RedVeil** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/679?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @bhanusanghi @leomarlo

**Comment by RedVeil** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/679?planning-poker) with ZenHub @arne-z

**Comment by Ajiva-D** [comment]
https://github.com/popcorndao/sweet-caramel/pull/731

**Comment by FanFanDAO** [comment]
@Ajiva-D PR 736 is not reviewable at this moment. As you mentioned, I need to go through the Create Proposal flow, which is currently blocked by the Step 4 popover (https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/51).
The "Lock & Submit" button is not working.

Please let me know as soon as this is resolved then.

**Comment by FanFanDAO** [comment]
Add website:
![Screen Shot 2022-06-30 at 1.18.20 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/5990d8bd-caf1-4217-a531-89f6ee26cd4f)

**Comment by Ajiva-D** [comment]
@FanFanDAO 
![Screenshot 2022-06-30 at 12.51.08.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/c4fd56fe-4d31-420a-998e-480a7b71db8d)
