### ISSUE TITLE
Gallery - Profile Detail Page with voting modal (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#681]
## Objective/Goal
We are coding the layout of the Profile Detail Page under the Gallery tab. This version is with the voting modal and is for a beneficiary to become an eligible beneficiary. The voting modal, the top nav, and the footer will be coming from different tickets therefore this ticket has three dependencies. 

## Specific Acceptance Criteria
- On clicking on the share icon on each image, an overlay of social buttons with options to share should appear
- image cards can be images, videos, and animated gifs
- please reference pinterest.com for format 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 10.22.27 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/6a5e600e-c9b8-4108-bb02-27de3d8317a3)
![Screen Shot 2022-05-06 at 8.55.48 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/969cad26-856a-41bb-9788-ea558ff4cbc7)

**Comment by RedVeil** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/681?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @bhanusanghi @leomarlo

**Comment by FanFanDAO** [comment]
@Ajiva-D PR 736 is not reviewable at this moment. As you mentioned, I need to go through the Create Proposal flow, which is currently blocked by the Step 4 popover (https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/51).
The "Lock & Submit" button is not working.

Please let me know as soon as this is resolved then.
