### ISSUE TITLE
01 Popover for Staking to Vote - Profile Detail Page (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#684]
## Objective/Goal
This popover shows up when the user clicked the "Stake to Vote" button from within the profile page of a beneficiary. This ticket is very similar to another popover and will only require copy changes. Therefore, there is a dependency on another ticket list below.

The only thing that is different is the starting copy. The starting copy for phase one, Open Vote, should be "In order to participate in the Open Vote, you need voice credits. Stake your POP to gain voice credits." The starting copy for phase two, Challenge Period, should be "In order to participate in the Challenge Period, you need voice credits. Stake your POP to gain voice credits."

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Make sure we follow the same popover styling we had created for under SC aside from the new functionalities and info.
- Clean, lean, and organized code practices
- Spacings, colors, shadow, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 11.48.24 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/87facb80-d706-4f2c-9197-d3cbfdcbaa15)
![Screen Shot 2022-02-10 at 11.48.09 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/72835e2e-c381-487a-ae74-37d23dd2d369)

**Comment by RedVeil** [comment]
![Screen Shot 2022-05-06 at 9.10.49 AM.png](https://images.zenhubusercontent.com/5d23b426292a4707ce2b61d3/6d20faa3-2709-4b14-bd79-f2568f9170bf)

**Comment by RedVeil** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/684?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @bhanusanghi @leomarlo

**Comment by FanFanDAO** [comment]
@Ajiva-D @arne-z This ticket is not reviewable. I could not reach this page from the singular [PR 624](https://deploy-preview-624--popcorn-grants.netlify.app/apply/form) provided today. Let me know when you have figured out a way for this to be reviewable. Many thanks!

**Comment by FanFanDAO** [comment]
@RedVeil Let me know then.
