### ISSUE TITLE
4x icon need to be created

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#688]

**Comment by FanFanDAO** [comment]
@annisharafi no, we need a logo design with 4X. The concept of this name comes because it literally sounds like "Forex" when you say 4X. 

## Key design focus
- Minimalistic and clean when viewed in 24x24px or even 20x20px
- Please check the list of Defi token icons for inspiration: https://coinmarketcap.com/view/defi/
- It should relate to our current branding. It doesn't been the current style of illustration since this is logo design.

**Comment by FanFanDAO** [comment]
@annisharafi @anthonymartin @RedVeil 
I got to have a design conversation with Michael about our temporary 4X icon yesterday. The decision came to that we should use the f symbol as well since it is related. My take and treatment to this are that we are using rounded corners for the icon and use orange to further itself from the Fixedforex blue or choosing anything blue. Have a look and let me know what you guys think.:)

![Screen Shot 2022-05-18 at 3.05.18 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3623a3d3-d5e4-4eaf-a186-0c43c6d6170c)

**Comment by RedVeil** [comment]
@FanFanDAO im fine with this. An X in there would be nice but i dont have a strong opinion here

**Comment by FanFanDAO** [comment]
![4x_icon.svg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/45b74d72-b234-4678-9d1b-7297713ea5eb)

Status: Done
