### ISSUE TITLE
SDK Adapter

### ISSUE THREAD

**Issue by mefuru** [popcorndao/sweet-caramel#690]
We want to list Popcorn on [Defi Llama](https://defillama.com/) and we need to write a SDK adapter that returns our TVL across all chains. (An adapter is just some code that takes in a UNIX timestamp and chain block heights, and returns the balances of assets locked in a protocol, including all the decimals (that is, the way it's stored on chain).

More background can be found [here](https://docs.llama.fi/list-your-project/submit-a-project). 

[This](https://docs.llama.fi/list-your-project/how-to-write-an-sdk-adapter) page contains a guide that we should follow.

Adapters for other projects can be found [here ](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects)

A basic adapter looks like this for context:

```
const sdk = require('@defillama/sdk');
const { transformBscAddress } = require('../helper/portedTokens');
const MINT_TOKEN_CONTRACT = '0x1f3Af095CDa17d63cad238358837321e95FC5915';
const MINT_CLUB_BOND_CONTRACT = '0x8BBac0C7583Cc146244a18863E708bFFbbF19975';

async function tvl(timestamp, block, chainBlocks) {
  const balances = {};
  const transform = await transformBscAddress();

  const collateralBalance = (await sdk.api.abi.call({
    abi: 'erc20:balanceOf',
    chain: 'bsc',
    target: MINT_TOKEN_CONTRACT,
    params: [MINT_CLUB_BOND_CONTRACT],
    block: chainBlocks['bsc'],
  })).output;

  await sdk.util.sumSingleBalance(balances, transform(MINT_TOKEN_CONTRACT), collateralBalance)

  return balances;
}

module.exports = {
  timetravel: true,
  misrepresentedTokens: false,
  methodology: 'counts the number of MINT tokens in the Club Bonding contract.'
  start: 1000235,
  bsc: {
    tvl,
  }
}; 
```

Acceptance criteria: The script returns our TVL as shown in our app for the following contracts:

Ethereum Contracts:
```
Butter V2	         0x109d2034e97ec88f50beebc778b5a5650f98c124
ButterStaking V2	 0x27A9B8065Af3A678CD121A435BEA9253C53Ab428
Butter	                  0xdf203cefcd2422e4dca95d020cb9eb986788f7ae
PopLocker	         0xeEE1d31297B042820349B03027aB3b13a9406184
RewardsEscrow	 0xb5cb5710044D1074097c17B7535a1cF99cBfb17F
PopUsdcLpStaking	 0x633b32573793A67cE41A7D0fFe66e78Cd3379C45
ButterStaking	         0x64337565e0Ce3E35fb7808C16807803a7540521C
```
Arbitrum:
```
RewardsEscrow	 0x0c0991cb6e1c8456660a49aa200b71de6158b85c
```
Polygon:
```
PopUsdcLpStaking	0xe6f315f4e0dB78185239fFFb368D6d188f6b926C
PopLocker	0xe8af04AD759Ad790Aa5592f587D3cFB3ecC6A9dA
RewardsEscrow	0xa82cAA79F35f7d6B6f1EC1971878F3474C894565
```
BNB:
```
RewardsEscrow	0x0C0991CB6e1c8456660A49aa200B71de6158b85C
```

Any questions, hit me up on Slack.

**Comment by bhanusanghi** [comment]
The PR has been merged into main on DeFi llama repo
https://github.com/DefiLlama/DefiLlama-Adapters/pull/2815
