### ISSUE TITLE
PIP-2 preparations

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#691]
ethereum:
* transfer aragon treasury to multisig
* transfer ownership of g-uni pool to multisig
* transfer USDC to Terra for staking on anchor
* update liquidity range on g-uni pool

polygon:
* create g-uni pool on polygon
* create comms for polygon liquidity migration
* deploy new staking contract
* update sweet-caramel with new staking contract
* update liquidity range on g-uni pool

**Comment by FanFanDAO** [comment]
@RedVeil 
Our frontend should replace all wording from "Gelato" to "Arrakis". Please let me know when this is updated. Many thanks! :)
