### ISSUE TITLE
polygon: add new arrakis staking contract to sweet caramel

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#696]

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/696?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @leomarlo @RedVeil

**Comment by anthonymartin** [comment]
* update deployment scripts
* add new staking contract to polygon frontend

**Comment by bhanusanghi** [comment]
Will be updating the getToken and buyToken links once we have those.
