### ISSUE TITLE
override contract metadata

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#699]
Sometimes it's necessary to update token names and symbols on the frontend. Let's think about doing this is an extensible and DRY way.

```
interface ContractMetadataOverride {
  [chainId: number]: {
    [contractAddress: string]: {
      name?: string;
      symbol?: string;
      description?: string;
      icon?: string;
    }
  }
}
```

whenever displaying token names or symbols, this override struct should be used before displaying the token metadata.

*Acceptance criteria*
* all existing implementation of token metadata display should use this struct
* updating the display text on the frontend should be as simple as updating the ContractMetadataOverride file

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/699?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @bhanusanghi @ecmendenhall @leomarlo @RedVeil

**Comment by bhanusanghi** [comment]
pr - [757](https://github.com/popcorndao/sweet-caramel/pull/757)

**Comment by RedVeil** [comment]
@bhanusanghi could you add icons in here?

**Comment by anthonymartin** [comment]
@RedVeil @bhanusanghi - I see the staking contracts are missing from here - these should be implemented as well
