### ISSUE TITLE
Update Terms & Conditions - Butter V2 Staking

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#701]
## Description
Butter V2 - We need to add a new term "Add: 90% of POP rewards are vested over one year. " 
​
## Specific Acceptance Criteria
- Copy to be added, "Add: 90% of POP rewards are vested over one year."

### General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![06052022-1.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c2cdef17-36a2-4138-88cc-5e07b46e510d)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://deploy-preview-773--sweet-caramel.netlify.app/ethereum
