### ISSUE TITLE
Sushiswap Migration Notification

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#703]
(**text to be included after the meeting)

![migration_ux_a.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3415675c-40ae-448f-8513-553add4a7568)
![migration_ux_d.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/6cbc81dc-3d58-4ad4-85ae-de6b84559288)
![migration_ux_c.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/68970e89-ff22-4aef-a440-3d46b4e6542a)
![migration_ux_b.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b8bdacfa-434e-482e-adde-4d306ead2690)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/703?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @bhanusanghi @ecmendenhall @leomarlo @RedVeil

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/713

**Comment by RedVeil** [comment]
This is missing some better copy and correct links to medium @anthonymartin

**Comment by FanFanDAO** [comment]
@RedVeil we need to replace all wordings from "Gelato" to "Arrakis".

**Comment by arne-z** [comment]
New PR: https://github.com/popcorndao/sweet-caramel/pull/783

**Comment by arne-z** [comment]
This only needs the publicly accessible link for the medium and then it will be ready for review.

**Comment by arne-z** [comment]
https://medium.com/@MichaelDKisselgof/d3cd5dd4c013
