### ISSUE TITLE
Product Iteration - Top Nav 

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#710]
## Description
Based on our user's request, we would like to bring out the network switcher and wallet connect button outside of the sandwich menu.
​
## Specific Acceptance Criteria
- Pre-connected state: white unfilled circle should be shown next to the network icon on the button, and an animation that fades-in upward should appear for the popover. This further educates the user that this button is where you connect your wallet and switch to another network
- When connected: a green dot should show up
- popover should be animation and slide in from the bottom of the screen
- For the network switcher within the popover, it is meant to be a scrollable wheel menu

## Resources
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=6750%3A28653

### General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
Design reference
![Screen Shot 2022-05-10 at 6.27.55 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/bfbbf280-3add-460f-9e61-3d13ec22c4e6)
Wheel menu reference
![screen_shot_2022-05-09_at_4.21.22_pm.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/cf2b01d5-c5cd-43c8-9fa5-89aee637e55b)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/710?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @leomarlo @RedVeil

**Comment by Amirjab21** [comment]
- tooltip defaulted to visible when wallet is not connected
- green light when wallet is connected

**Comment by FanFanDAO** [comment]
let me know how this goes @Ajiva-D

**Comment by Ajiva-D** [comment]
Alright, I'm picking it up next

**Comment by Ajiva-D** [comment]
@FanFanDAO https://deploy-preview-933--sweet-caramel.netlify.app/

**Comment by FanFanDAO** [comment]
@Ajiva-D so there is no way to modify and adjust the top and bottom spacings for this plugin? The default network should be Ethereum. Maybe you want to reorder the menu?

**Comment by FanFanDAO** [comment]
@Ajiva-D so there is no way to modify and adjust the top and bottom spacings for this plugin? The default network should be Ethereum. Maybe you want to reorder the menu?

**Comment by anthonymartin** [comment]
@Ajiva-D can you respond to Fan's question above? Also I noticed that the icons are missing which are shown in the design references.
