### ISSUE TITLE
Expose mainnet circulating supply via an API endpoint

### ISSUE THREAD

**Issue by mefuru** [popcorndao/sweet-caramel#716]
**Background:**
Currently, [Coingecko](https://www.coingecko.com/en/coins/popcorn) obtain their circulating supply from a spreadsheet I've created that lists unlocked amounts from our [Aragon node](https://client.aragon.org/#/popcorn/0x50a7c5a2aa566eb8aafc80ffc62e984bfece334f/). It's janky and I'd like to replace the source for unlocked tokens on ethereum to the spendable balance as per `packages/hardhat/lib/tasks/aragon/spendableBalanceOf.ts` . (Related [PR](https://github.com/popcorndao/sweet-caramel/pull/668/files))

**Acceptable criteria**
It would be great if someone could expose the balance returned by the above script as an api endpoint on our netlify/vercel deployment. 

Hit me up with any questions via Slack.

Thanks!

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1076

**Comment by anthonymartin** [comment]
the api endpoint is failing: - can you review @Amirjab21 ? ![Screen Shot 2022-08-08 at 4.40.27 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/18744325-ebf0-42d6-92ad-d88b0671f381)

**Comment by Amirjab21** [comment]
Fixed the error, and currently it downloads the csv to images/ in the popcorn folder.

**Comment by Amirjab21** [comment]
Note: a lot of environment variables need to be added for this to work.

**Comment by anthonymartin** [comment]
@Amirjab21 - please send over the csv for this when you get a chance

**Comment by Amirjab21** [comment]
heres the csv [Uploading... popx.csv]
Total circulating supply: 23209557.05247078

**Comment by anthonymartin** [comment]
psuhing back to @Amirjab21 to fix the timeout issues with the endpoint

**Comment by anthonymartin** [comment]
@RedVeil could you add the env vars to this in vercel to check the api returns correctly, and if all is good, then add them to prod env vars and merge this one in
