### ISSUE TITLE
Landing Page for Sweet Vault Launch 

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#739]
We need the landing page where it says 4X to be duplicated and make another design for Sweet Vault. 

Idea 1) A cocktail illustration. A cocktail is sweet and it can be made into different flavors. 
Idea 2) Illustration of a normal concept of vaults

If you have better ideas, do try them out also.

![Screen Shot 2022-05-19 at 4.56.21 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/cbfd1f5f-957d-47e5-96e7-11ff78e24b20)

**Comment by annisharafi** [comment]
here's an update fan @FanFanDAO 
1. version 1
![image](https://user-images.githubusercontent.com/22950097/169458169-f8eb6a71-d94a-41bc-ade5-b951eb673099.png)


2. version 2
![image](https://user-images.githubusercontent.com/22950097/169458227-6e68d954-969c-42cb-9dac-be4c0ec47786.png)

**Comment by FanFanDAO** [comment]
@annisharafi Maybe add some small popcorns next to the cocktail? :)
Note: 4X is not going to be ready so we are only having three products in the upcoming launch.

**Comment by annisharafi** [comment]
updated @FanFanDAO 
![image](https://user-images.githubusercontent.com/22950097/169545514-4f516ee7-29d4-4f83-96e8-330ce3c3192e.png)

**Comment by FanFanDAO** [comment]
@annisharafi I think the blue from the cocktail make mixer is really strong. Also, we shouldn't change the Staking image since we are only working on the Sweet Vault image. Can you also provide a screen on the pop locker illustration as a second option as well? We need both versions for others to compare with.
