### ISSUE TITLE
Transaction Notifications Cards

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#741]
## Description
The current live notification frontend styling is not close to the original design we had from before. We should update them. Please check the reference images below.
​
## Specific Acceptance Criteria
- Same animation and transition as what we have coded
- Ideally, the end position of the notification card on the desktop should right align with the Disconnect Wallet button.
- On-chain data input to reflect transact values from one coin to another
- Digit references: 0.00 or 0.000000
- create new class of notifications which receive Title, Description (optional), Type properties.
- update all existing notifications to use new notification class
- show design A when description is provided, or Design B when description is not provided

​
## Resources
_This should have a Link to the specific element in Figma, or any other resources that should be referenced (e,g, guides, libraries if applicable)_
https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

### General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-05-19 at 11.01.24 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/aab3b89a-7a51-4a4d-9a92-86124365f5b1)
![Screen Shot 2022-05-19 at 11.09.06 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f11d2acf-a30e-48bb-8f55-11b2056feecf)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/741?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @bhanusanghi @ecmendenhall @leomarlo @RedVeil

**Comment by Amirjab21** [comment]
I've made great progress on the UI elements for this ticket. The final thing left to do is actually grab the numbers from certain transactions to pass through to the notification handler.

Am I doing this just for butter mint functions? @RedVeil  @anthonymartin

**Comment by FanFanDAO** [comment]
@Amirjab21 @anthonymartin 
With Metamask, my experience is that we always get the "Confirmed Transaction: Transaction 3 confirmed. View on Etherscan" Can we somehow brand this experience with our own design?

**Comment by Amirjab21** [comment]
PR:
https://github.com/popcorndao/sweet-caramel/pull/800/

Screenshot:
![Screenshot 2022-06-09 at 15.15.09.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/1ab2af00-b9b6-4049-b9ec-f36b9d341cc7)

**Comment by FanFanDAO** [comment]
@Amirjab21 Let's use this image :)
![Group 842.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/6c4cb1d3-3c89-425e-a879-e27514457ac)

**Comment by FanFanDAO** [comment]
@Amirjab21 The spacing and font weight need to be looked at:
Your screenshot:
![Screen Shot 2022-06-10 at 3.12.46 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9caa0914-4202-4b8b-9e47-ec511870a0f6)
Our design:
![Screen Shot 2022-06-10 at 3.13.22 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d1f23b2b-63a5-43c8-bf14-5aafa03e0718)

**Comment by RedVeil** [comment]
@Amirjab21 left some comments

**Comment by Amirjab21** [comment]
@FanFanDAO @RedVeil 

design: The design I've used is consistent with the other notifications e.g
![Screenshot 2022-06-20 at 12.50.14.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/cfc3dce8-a8ad-429a-b7ae-bb314ae076e7)

I can align it to the design you posted but just letting you know that it will be different to the other notifications on the website.

I think you may be correct that we don't actually get the BTR amount from the notification so how should we display it without the BTR amount?

**Comment by Amirjab21** [comment]
Theres a problem with this ticket 
the toast.custom() method doesn't interact properly with tailwind and we therefore can't replicate the animation of the normal toast notifications

Heres the issue:
https://github.com/timolins/react-hot-toast/issues/116

**Comment by Amirjab21** [comment]
![Screenshot 2022-06-23 at 18.18.31.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/c2b66a70-5fcd-4b87-b185-ad0ef106049f)


fixed it

**Comment by RedVeil** [comment]
@Amirjab21 Finally left some comments. Great PR though

**Comment by Amirjab21** [comment]
I think this PR is going to have to be replaced by wagmi/useDapp so it may be blocked for now.

**Comment by RedVeil** [comment]
New PR https://github.com/popcorndao/sweet-caramel/pull/1171

**Comment by FanFanDAO** [comment]
Hi Leon, can you attach a screenshot since I couldn't simulate this without performing an actual transaction? I want to make sure that the styling is correct to our rebrand look with the right fonts and spacings.
![Screen Shot 2022-09-02 at 1.04.04 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ef8c2216-dca1-4151-8e04-af555f8efae6)

**Comment by arne-z** [comment]
I've reviewed the code and it looks good, really liking the cleanup in the Settoken pages as well!
I am getting a bunch of errors on the frontend though when viewing the deployed preview connected to hardhat/localhost. Is there an issue there that we need to address? The same hardhat instance works fine in conjunction with new-website branch.
