### ISSUE TITLE
Reward Page - Introduce new design to incorporate data for Total Vesting Token

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#749]
Our design currently only shows the total claimable token at the top. The user wants to see the Total Vested Token so they don't have to do the manual calculation from looking at every single record. Let's work on the Explore page on this and see what is a better ux for this.

**Comment by annisharafi** [comment]
updated @FanFanDAO, let me know what you think
![image.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/f8c0c107-1693-4d39-ab1a-a20ea93dea60)

**Comment by annisharafi** [comment]
updated @FanFanDAO, let me know what you think
![image.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/f8c0c107-1693-4d39-ab1a-a20ea93dea60)

**Comment by FanFanDAO** [comment]
@annisharafi Interesting! We might need to check and see how this UX looks on mobile. 
We need to say Total Claimable Token to make it clear to the user.

For the illustration:
Total Vested - Let's try a lock since it is not ready to be claimed. The current illustration feels like downloading
Total Claimable Token - Let's have a minimalistic circular icon to represent token

**Comment by FanFanDAO** [comment]
@anthonymartin Annisha is on holiday but here is the latest mock. She is yet to address my feedback above but we can reference the UX here.
![after.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/56408a0b-4ff4-48f3-b937-a5d5ce4318e8)

**Comment by annisharafi** [comment]
here's update based on the latest feedback fan
![Screen Shot 2022-06-02 at 22.20.19.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/9d0f35a6-571e-48b8-9646-9fed42ca04ec)

**Comment by annisharafi** [comment]
updated @FanFanDAO 
![Screen Shot 2022-06-02 at 23.02.07.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/ca44998a-f5f2-4315-a2c7-e66e254d2655)

**Comment by FanFanDAO** [comment]
@anthonymartin the design is ready and above this comment.

**Comment by FanFanDAO** [comment]
@anthonymartin Our latest design update based on the last Slack conversation:
![A.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/fae7583e-0748-4557-98a4-55009ded8340)
![B.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a5b9258f-35a0-4a79-a57d-41010fab61cd)
