### ISSUE TITLE
All found APY should now be written as vAPR

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#764]
## Description
We are updating our UX language here to a more adequate terminology. The vAPR info tooltip should trigger a popover. This is a more advanced version as compared to our normal tooltip popover so please do check the reference images below.
​
## Specific Acceptance Criteria
- Update text APY to vAPR on the below:
1. Butter detail page
2. Staking detail page
3. 3X detail page
- The info tooltip should trigger a popover 

## Resources
Copy:
BTR:
How we calculate the APY: This is the estimated Annual Percentage Yield. The shown APY comes from yield on the underlying stablecoins (1.32%) and is boosted with POP (11.25%). You must stake your BTR to receive the additional APY in POP. 90% of earned POP rewards are vested over one year.
3X:
How we calculate the APY: This is the estimated Annual Percentage Yield. The shown APY comes from yield on the underlying stablecoins (1.7%) and is boosted with POP (-0%). You must stake your 3X to receive the additional APY in POP. 90% of earned POP rewards are vested over one year.
Staking:
Est. APY:: This is the estimated Annual Percentage Yield. 90% of POP rewards are vested over one year.
Figma:
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=6750%3A28653

### General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-05-27 at 3.26.14 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/502e4f30-d664-4a05-a8cc-db2261a84b79)

**Comment by arne-z** [comment]
Current Tooltip:
"Est. APY:: This is the estimated Annual Percentage Yield. 90% of POP rewards are vested over one year."

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/868

**Comment by anthonymartin** [comment]
@Amirjab21 - left a comment on the PR #868

**Comment by Amirjab21** [comment]
Removed uppercase from the StatusWithLabel component so that you have to write the string literal with the final casing.

**Comment by FanFanDAO** [comment]
@Amirjab21 Let's use vAPR instead of "Est vAPR". The letter "v" represents "variable". This is good enough to suggest the prompt-to-change factor about the APR. This ticket was a bit dated when I first wrote it, but with my later research, it seems that APR is the most commonly used term in Defi, but Convex uses vAPR, which is clearer, and we will go with this.

**Comment by FanFanDAO** [comment]
@Amirjab21 the PR doesn't load for me. It keeps showing a blank page. caw we check?

**Comment by Amirjab21** [comment]
I pushed again with one final copy change from Anthony - It should work now.

If it doesn't, its a problem with the develop branch/deploy process as I've only changed text in this PR so it can't possibly break it

**Comment by anthonymartin** [comment]
@Amirjab21 can you update this so we keep the css rule for uppercase? we can wrap the v in a <span> with a rule to lowercase it. This is also a merge conflict - would you be able to resolve that?

**Comment by anthonymartin** [comment]
it should be a <span> and not a <p>, but that's the idea

the reason to keep the uppercase css is to avoid future issues where a developer mistakenly puts in lowercase or mixed case values messing with the style.  in this way, the solution I proposed is future-proof and anti-fragile

**Comment by anthonymartin** [comment]
@Amirjab21 the interface should allow a `string |  React.ReactElement` to be passed as an argument to maintain backwards compatibility also
