### ISSUE TITLE
Educational vAPR popover

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#765]
## Description
This popover explains to the user how our Butter vAPR percentage is broken down, how is it being calculated and what is vAPR. This creates educational value and transparency.
​
## Specific Acceptance Criteria
- Create the layout for vAPR popovers for both desktop and mobile
- Add text link "Manage your rewards now on Rewards Page"
- All cards should be in their collapsed state to begin with
- Link all live fetch data to each data we want to display (certain data needs to display their value minors all the fees)

**Butter vAPR**
1. **Base APR**: Total of the four pool vAPR/4 (The value for Base APR should be without all the fees)
2. **Pop Boost**: Our coded percentage

**yvCurve-FRAX** : 1+2+3
(*CRV vAPR, and CVX vAPR should have the 17% convex fees and 22% yearn fees taken out)

1. **Base Curve vAPR**: refers to the share of the transaction fees from depositing your funds in Curve Pools (most stable yield but small)
2. **CRV vAPR**: refers to the reward from LP in Curve. It has a minimum of 3% and max of 7.58% currently depending on the amount the user deposits
3. **CVX vAPR**: staking with Convex earns the additional CVX rewards

## Resources
Design File:
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=7294%3A25947
Data sources & Convex fees(Search on Convex and click the tooltip next to the vAPR of the pool):
https://www.convexfinance.com/stake
Yearn fees: 
https://docs.yearn.finance/getting-started/products/yvaults/overview

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![vAPR_popover_desktop.jpg.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/7601b7f9-fdae-4837-8546-f358be0d2cd4)
![Butter_vAPR_mobile.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/65c2a098-f09d-412e-93cc-e9a1fc9348cc)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/765?planning-poker) with ZenHub @Ajiva-D @arne-z @bhanusanghi @ecmendenhall @RedVeil
