### ISSUE TITLE
Popover - Time to Restake 

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#777]
## Description
With our current contract model, the user needs to comply with this term "Your staked tokens must be re-staked or withdrawn after the 3-month lock time expires, or they will be subjected to a penalty of up to 1%. "To increase awareness and better our user experience, we are adding a popover that would show up on the last week before the expiration date and at each wallet login until the user has taken the either-or actions.
​
## Specific Acceptance Criteria
- The layout of the popover should be created
- The action logic of either CTA should be established
- The popover should show up upon connecting to the wallet in the last week until an action has been performed.
- Use the copies under Resources
- Add hotlink for /ethereum/staking/pop/withdraw & /polygon/staking/pop/withdraw
​
## Resources
**Title:** It’s time to restake!
**Main Copy:** Your POP tokens must be re-staked or withdrawn after the 3-month lock time expires or they will be subjected to a penalty of 1% per epoch week that they are not re-staked
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=2253%3A29429

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-06-01 at 6.17.26 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/14bdac76-f326-4f72-a523-35026c5076dd)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/777?planning-poker) with ZenHub @Ajiva-D @arne-z @bhanusanghi @ecmendenhall @RedVeil
