### ISSUE TITLE
support network agnostic pages

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#779]
Pages like the landing page should not redirect to a default chain. The router should recognize some pages as network agnostic and not force a rewrite, as well as not display a modal wrong chain modal if the wallet is connected to a wrong network (such as on the landing page)

**Comment by RedVeil** [comment]
- Track which network a user was on before a user visits the landing page

**Comment by RedVeil** [comment]
Should the url for the landing page also be chain agnostic (dont show popcorn.network/[network])? @anthonymartin
