### ISSUE TITLE
Update Staking terms on Figma

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#789]
## Description
We have three staking products ( POP, LP, and Butter V2), and the terms are different and listed below. Please update terms to all screens and create screens with the appropriate product terms.
You can check popcorndao.finance for detail

For LP and Butter staking term:
1. After rewards are earned and claimed, 10% is immediately transferred, and the rest of the earned amount is unlocked linearly over the following 365 day period.

POP staking terms:
1. Your staked tokens will be locked for a period of 12 weeks. You will be unable to access your tokens during this period.
2. Your staked tokens must be re-staked or withdrawn after the 3-month lock time expires or they will be subjected to a penalty of 1% per epoch that they are not re-staked.
3. After rewards are earned and claimed, 10% is immediately transferred, and the rest of the earned amount is unlocked linearly over the following 365 day period.

**Comment by annisharafi** [comment]
updated @FanFanDAO , I also tag you in comment #120
