### ISSUE TITLE
Adjustment to the Butter Mint Card

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#797]
## Description
We have introduced Mint & Stake button as a new function, and we need to explain that to the user. As a result, a new layout with spacing adjustment has been made so that it fits our current design system. 
​
## Specific Acceptance Criteria
- Make sure spacing is looked at closely
- The size of the tooltip inside the expanded Adjust Slippage panel in the current live site is not sized correctly. Please fix this.
- Use unclaimed balance checkbox is missing on the current live site
- Make sure all on-hover tooltip modals work

## Resources
Under the "Form" Page in our Design System
https://www.figma.com/file/5bmpYjaYkpoefISS9afbHc/Design-System?node-id=6502%3A4690

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![screen_shot_2022-06-09_at_1.38.49_pm.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ea43e7e5-b863-4ad6-a771-c68f98b745be)

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/834

**Comment by FanFanDAO** [comment]
@arne-z Hey Arne, I tried to click approve but then the POP testing account doesn't have enough eth.
