### ISSUE TITLE
Modal for "Mint & Stake vs Mint"

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#798]
## Description
Create an on-hover modal for "Mint & Stake vs Mint" from within the Mint panel on Butter product landing page.
​
## Specific Acceptance Criteria
- Create a on-hover tooltip modal, which we already had the style for
- Use copy "Choose Mint & Stake to automatically stake the token to earn POP rewards. If you select Mint you will not earn POP rewards unless the token is staked in the [staking](/ethereum/staking) page."

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

**Comment by arne-z** [comment]
See PR in https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/797
