### ISSUE TITLE
Butter - "How It Works" image update for Step1-3 (add images with halo)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#801]
## Description
We need to update the step1-3 image in How It Works carousel so that it reflects the correct notification system and Your Batch list.
​
## Specific Acceptance Criteria
- replace with the below images
- replace/add images on both Butter & 3X
​
## Resources
![BTR_Step1.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/172c4ba0-5561-4dbe-a4b3-254b705f2c3d)
![BTR_Step3.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/53031b56-c6a5-45b7-9a86-5cb5a087defb)
![3X_Step1.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c4273cba-6636-4414-923c-490ed69f8f8c)
![Step2.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8a7e2421-290b-4c5e-9a28-3d43c6b844f9)
![3X_Step3.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/4381c7fe-02bf-4547-9d7d-3ed90183fbf6)

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-06-09 at 5.31.37 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/bd5903e4-b9e9-40a3-8bc0-2860a363c5b9)

**Comment by RedVeil** [comment]
@FanFanDAO Can you add the images with halo in this ticket?

**Comment by FanFanDAO** [comment]
Image updated :)
