### ISSUE TITLE
Update popcorndao.finance landing with TVL and Social Impact Stats

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#829]
## Description
We are adding two cards to our popcorndao.finance landing. One would show TVL stats, and the other would show the user's net worth (My Net Worth) Both on-hover tooltip modals should work properly.
​
## Specific Acceptance Criteria
- Layout of the page
- Make sure both on-hover tooltip modal works
- Make sure the My New Worth card shows "Connect your wallet" in the pre-wallet connect state
- Copies 
**TVL**: To put it simply, total value locked represents the number of assets that are currently being staked in a specific protocol: this value is not meant to represent the number of outstanding loans, but rather the total amount of underlying supply that is being secured by a specific application by DeFi completely.
**My Net Worth**: My net worth is the sum of all products a user has participated in the Popcorn ecosystem across all applicable networks. This number also includes the total vesting and claimable rewards.
​
## Resources
Under the Explore tab:
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=7514%3A28360

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![7.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3577880c-b219-41b4-842f-da1a15dbd2a8)
![5.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ae1a3e50-ee0f-435d-921f-f91eea4213ab)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/829?planning-poker) with ZenHub @Ajiva-D @arne-z @bhanusanghi @ecmendenhall @RedVeil

**Comment by FanFanDAO** [comment]
@bhanusanghi, when you got the contact from Defillama can you notify me here?
