### ISSUE TITLE
Bug - Buttons broken on the Coming Soon Popover (Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#861]
## Description
When you try to access the "butter" page while being connected to Polygon you will see that "coming soon" dialog. (Android & MetaMask browser). However, the buttons look broken (UI-wise). Also, it takes ages for the buttons to react to your input. (Please check image below on the bug)

## Specific Acceptance Criteria
- Please make sure all button works on iOS, Android, and MetaMask Browser
- Layout should reflect our design 
- Switch Network button should be in the secondary button styling

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![82ffbac819a51598e52a8223849f8af2.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/93c77ca1-7bbb-4f36-84fc-3cad5f9df4e4)

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/870

The performance issue is because of the code that is intentionally set when confirming or dismissing the modal:

const confirm = () => { setOpen(keepOpen); setTimeout(() => onConfirm?.onClick && onConfirm.onClick(), 1000); };

We're waiting a second before activating this function - I think this was a fix to stop some kind of bug if they clicked on the modal too soon.

So not sure what we should do - could reduce it to half a second? or just leave it?

**Comment by anthonymartin** [comment]
perhaps we can reduce it to 500ms. It was implemented to allow time for the css transition. I'm not sure if 500ms is too short though

**Comment by Amirjab21** [comment]
@anthonymartin reduced to 500ms which has made it smoother and it still works fine.

**Comment by anthonymartin** [comment]
@Amirjab21 - the deploy preview is not working here. can you take a look? maybe it needs a pull from develop

**Comment by Amirjab21** [comment]
Merged from develop and now it works fine @anthonymartin

**Comment by FanFanDAO** [comment]
@Amirjab21 
![Screen Shot 2022-07-11 at 3.00.53 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b0ad7371-61a0-4ecc-852c-69fe856090ce)

**Comment by Amirjab21** [comment]
![Screenshot 2022-07-12 at 11.44.15.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/652be22d-43d1-47ac-96ac-4c2ce7c9c6f8)

![Screenshot 2022-07-12 at 11.42.28.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/a33352ab-4134-4470-be8e-373f963a3431)
