### ISSUE TITLE
Bug - Digits overrun the Staking input field (Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#862]
## Description
When you try to stake some SLP via Android & MetaMask browser the amount input field overflows the "max" button. (Please check the reference image on the issue)
​
## Specific Acceptance Criteria
- Make sure this does not happen on iOS, Android, and MetaMask Browser

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![8cad5b37e0fb905e99fd766273dfb13f.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ca08373b-8c30-4869-8335-de053af9b8e1)

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/894

**Comment by FanFanDAO** [comment]
@RedVeil Here is a video where I demo the problem with the current treatment:
https://www.loom.com/share/fb3b93bf6f484e6bbed39c0f4a8a3a18
Can we do this?
3: Gray 500
9: Gray 400
...: Gray 300
![Screen-Shot-2022-06-27-at-2.00.44-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f732219d-583a-4eb2-ac90-9c5265183be4)

**Comment by FanFanDAO** [comment]
@RedVeil Any update?

**Comment by FanFanDAO** [comment]
@anthonymartin are you able to make this change?
