### ISSUE TITLE
Bug - Mobile menu does not work properly (Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#863]
## Description
1) I can't switch the webpage's current page (staking/butter/rewards) via the mobile menu. The selected page is highlighted. However, the content of the page does not change. (Please check the reference image below on the issue)

2) Fan: On iOS Metamask browser, when I select from "Home" to "Butter" in the mobile expandable menu, it doesn't automatically animate out / close the menu to reveal the Butter landing page. 

## Specific Acceptance Criteria
- Make sure all linked pages will show upon clicking or fresh and change from one page to another in the mobile expandable menu across iOS, Android, and Metamask Browser.
- Make sure the expandable menu hides or animates back to close and reveal the clicked page 

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![772b847fa0b6c2f8bbd6bc00161043b5.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c038e819-73b7-4433-9e47-732c5a866e96)

**Comment by Amirjab21** [comment]
PR: 
https://github.com/popcorndao/sweet-caramel/pull/869

**Comment by anthonymartin** [comment]
> a useEffect which sets the menu to false every time the router.pathname changes.
this seems like the most elegant way with the least amount of code. also devs don't have to remember to add an extra function for each link
