### ISSUE TITLE
network inconsistency popup should support unsupported networks

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#878]
## Description

1) If the user is on Avalanche network in Metamask and we do not support it, a popover to switch networks should automatically show up. 

* for better UX, we should create a mapping of chain ids to network names for displaying modal to user
​
## Specific Acceptance Criteria
- Get issues 1 to work within the Metamask browser

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Video References
Manual switching required currently:
https://www.loom.com/share/2d110dfa1bc24dad9c0082eb0745603e

**Comment by arne-z** [comment]
![Screenshot_20220701_154912.png](https://images.zenhubusercontent.com/5c6e9b98b3d46374d6a0d6b3/d52769a4-d1f2-4fd5-a0fe-69adbefe564f)

**Comment by Amirjab21** [comment]
How about this?
![Screenshot 2022-07-18 at 17.57.20.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/a803512f-057e-45ed-b187-3e9bd9cbb514)

I thought it might be best not to offer the option for them to continue on their unsupported network as it will take them to /unsupported_network/page

**Comment by anthonymartin** [comment]
@Amirjab21 makes sense

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/967
