### ISSUE TITLE
Bug- After staking, the number of POP tokens doesn't automatically display on the Your Staked Balance

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#880]
## Description
After staking, the number of POP tokens doesn't automatically display on the Your Staked Balance unless a force page refresh was performed
​
## Specific Acceptance Criteria
- Staked POP token should immediately display on the "Your Staked Balance" card without having to refresh within the Metamask browser

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Video References
https://www.loom.com/share/b5c2e4490ff54dd2b61697b8a4e51099

**Comment by arne-z** [comment]
@bhanusanghi contrast how the state is updated on this page vs. on staking:
https://github.com/popcorndao/sweet-caramel/blob/develop/packages/app/pages/%5Bnetwork%5D/butter/threex.tsx

The issue that occurs is probably that the state is set twice in short succession and the second state update overwrites the first, this can be prevented using the arrow function setState syntax.
E.g. `setState(state+1)` vs. `setState( state => state+1 )`.

**Comment by bhanusanghi** [comment]
https://github.com/popcorndao/sweet-caramel/pull/907

**Comment by FanFanDAO** [comment]
@anthonymartin can you help check on this and get this merged? I am not sure if the PR would show me anything. Is there a way to validate, or do we have to stake it again to find out? Not sure if I should stake with a PR link. Let me know.
