### ISSUE TITLE
Bug - 3X Layout spacings issues (Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#885]
## Description
The mobile layout is breaking. Please look at the reference image and video below.
​
## Specific Acceptance Criteria
- Fix all spacings
- Make sure the copy in the batch card does not run over to the column where the info tooltip is. "Your request will be processed with the next batch."
​
## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## References
Loom video: ( If this is your first time viewing a Loom video, please ask me for viewing access.)
https://www.loom.com/share/4bf3dac066de40878c34895333c81902
Image references:
![Screen Shot 2022-06-23 at 5.08.52 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c1180fa7-f01c-4417-b510-f6868ae57a10)
![Screen-Shot-2022-06-23-at-5.10.10-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/fa65d801-91c2-4931-b1f3-5631ca49748e)
![Screen Shot 2022-06-23 at 5.34.19 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ce9bdcd9-9d59-48d7-aae6-9d3e9ab77e9f)

**Comment by Ajiva-D** [comment]
@FanFanDAO 
![Screenshot 2022-07-05 at 11.03.44.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/d20748d0-11b1-4211-8b93-268b820e48ff)
![Screenshot 2022-07-05 at 11.03.55.png](https://ima![Screenshot 2022-07-05 at 11.04.10.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/5536fc23-2641-42cc-b66b-df727201ed9b)ges.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/2a3f93c0-a7c6-40a3-be94-c45d4015336e)

**Comment by Ajiva-D** [comment]
![Screenshot 2022-07-05 at 11.03.55.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/6849d6ec-8719-4ee9-829f-463eb1775a56)

**Comment by Ajiva-D** [comment]
@FanFanDAO 
![Screenshot 2022-07-05 at 14.59.40.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/ecaae6a0-ba9c-41ed-9a4c-f1c920fcdd42)

**Comment by Ajiva-D** [comment]
![Screenshot 2022-07-05 at 14.59.34.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/acf9015f-4c23-415a-93e4-73d12b8b7c94)

**Comment by FanFanDAO** [comment]
@anthonymartin Arne has merged the latest PR for this ticket, according to David. The last design was checked through screen share. :)
