### ISSUE TITLE
Bug - 3X & Butter Your Batches are still in the old styling (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#887]
## Description
Your Batches table is not styled properly. Please look at our Figma file and the reference images below.
​
## Specific Acceptance Criteria
- Please style it like our Figma design
​
## Resources
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=7854%3A29317

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
Currently on our website:
![Screen Shot 2022-06-23 at 5.36.51 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8eaec40f-eaf5-48e3-b03e-59d1d62bf3c6)
Figma design:
![Screen Shot 2022-06-23 at 5.39.35 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f3cad9c8-acab-4fc1-9093-1f81017c102b)

**Comment by FanFanDAO** [comment]
@Ajiva-D Let me know when I can review this then. :)

**Comment by Ajiva-D** [comment]
@FanFanDAO 
![Screenshot 2022-06-30 at 14.09.15.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/135776f4-10c1-4354-87a9-0a55dbabd541)

**Comment by Ajiva-D** [comment]
@FanFanDAO 
![Screenshot 2022-07-04 at 10.10.25.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/52699a70-d7a0-44db-a5bf-4f988dc8b0dc)
