### ISSUE TITLE
Eagerconnect to Gnosis Safe

### ISSUE THREAD

**Issue by arne-z** [popcorndao/sweet-caramel#915]
Adjust Eagerconnect to detect when the page runs embedded as a Gnosis safe app and automatically connect to the gnosis wallet. 
This should take precedence even if the user has last used metamask or another wallet.

Intuitively it should be possible to detect running in gnosis through the router, but there might be a different way. 
If we do use the router to detect the gnosis environment, we need to be conscious of the timing since local storage eagerconnect settings will usually be loaded before the router is ready.

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/915?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/762
