### ISSUE TITLE
Frontend for Instant 3x

### ISSUE THREAD

**Issue by arne-z** [popcorndao/sweet-caramel#918]
Update the 3x frontend to make instant 3x usable. This should be done exactly like instant butter.
This includes adding a separate Instant page for 3x as well.
As part of this ticket, we need to fix a behavior in the MintRedeemInterface where the dropdown to select and output currency is disabled in instant redeem on butter.

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/918?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall

**Comment by anthonymartin** [comment]
@RedVeil I'm pushing this back over to you since the frontend is breaking - I think named accounts needs to be updated

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/1001

**Comment by RedVeil** [comment]
Addressed it. One thing that i discovered is that on localhost atleast on my machine it takes a while until the contract get their signers. So approvals will instantly fail. If you wait a little this resolves it self. Dunno why this is happening on localhost. 
I tested it with prod on localhost. Same result but the deployed version runs fine so it seems to be just a localhost issue.

**Comment by anthonymartin** [comment]
@arne-z could you feature flag this so we can enable after the contract is deployed?

**Comment by anthonymartin** [comment]
@arne-z can you resolve the conflicts?

**Comment by arne-z** [comment]
@anthonymartin resolved
