### ISSUE TITLE
Bug - Add a dimiss button to Time to Restake

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#928]
## Description
Make sure people can click on the negative space outside the card to exit the popover. Also, we are adding a dismiss button to this popover to emphasize that it is not an either-or forceful choice. 

If the switch network popover appears, the restake popover should come after. This means network switching popover always takes priority. We should not show two popovers at one time but rather one after another if the situation applies. 
​
## Specific Acceptance Criteria
- Add the dismiss button on this popover
- make sure people can click on the negative space to exit this popover as well
- If the switch network popover appears, the restake popover should come after. This means network switching popover always takes priority. We should not show two popovers at one time but rather one after another if the situation applies. 
​
## Resources
https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=2253%3A29429

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-07-05 at 7.12.27 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/697da760-2c5c-4c81-80ca-8780a3672cdb)

**Comment by Amirjab21** [comment]
PR:
https://github.com/popcorndao/sweet-caramel/pull/932
