### ISSUE TITLE
make 3x batch processing and butter batch processing permissionless

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#949]
We would like to automate 3X and Butter batch processing so anyone can call a batch while keeper incentive updates are made.

* update keeper incentives for 3X/Butter to allow anyone to call it
* create hardhat task for 3X and Butter to run batchMint/batchRedeem every 24 hours

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/949?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @ecmendenhall @K-G-J @RedVeil

**Comment by Amirjab21** [comment]
Provisional PR: https://github.com/popcorndao/sweet-caramel/pull/961

We still need to decide where the cron-job will live. Are we going to add a server to our Nextjs app? What architecture preferences do we have? I can make a custom server at the root of the /app folder like this example:
https://github.com/vercel/next.js/tree/canary/examples/custom-server-express

Also, Anthony or someone else with the DAO_ROLE needs to actually run the hardhat task that changes the approval required for these selected incentives. I've provided two example bash scripts so this can be done very quickly.

When we've decided with the server architecture, I can just create an express server and schedule cron-jobs using an npm package like https://www.npmjs.com/package/cron

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/961

There are two .sh scripts in there with examples of how to run the toggleApproval task call to make the batchMint and batchRedeem permissionless (note that you have to run it with network localhost for it to interact with your local hardhat node)

The tasks for batchMint and batchRedeem don't take any arguments so I haven't left an example script.
