### ISSUE TITLE
replace native img tags with next images

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#956]
## Description

Currently, the UI has a slightly degraded experience because images aren't being preloaded with next image tags with preload enabled. By replacing all instances of native img tags with preload enabled  next image, then the UX will be enhanced.

## Acceptance Criteria

All native img tags should be replaced with preload enabled next images in the following areas: 
* all modals where images exist (mobile and desktop)
* all select inputs with options/dropdowns - this includes on `/set/butter/` /set/3x`, network selector in navigation (mobile and desktop)

## Related tickets

#888

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/981

**Comment by anthonymartin** [comment]
one of the images is not loading correctly on the /staking/[id] page : ![Screen Shot 2022-08-08 at 4.43.51 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/85e658d5-2b22-4922-8ed0-d2bc4435775c)

**Comment by RedVeil** [comment]
addressed

**Comment by anthonymartin** [comment]
I'm pusshing this one back to you since we discussed it will be necessary to update the reveal pattern to use css instead of not rendering the content

**Comment by anthonymartin** [comment]
set this one to blocked-  it probably makes sense to address this when rebrand is complete
