### ISSUE TITLE
page doesn't update after zapping into butter batch

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#957]
Expected behavior: When zapping into a butter batch for minting, on transaction confirmation, a success toast notification should be displayed, the page content should update and the batch table should include the latest deposit

Observed: When zapping into a butter batch for minting, no success modal/toast notification is displayed and the batch table does not update.

**Comment by Amirjab21** [comment]
What environment was this on? It seems to be working on localhost for me right now.
![Screenshot 2022-07-18 at 15.41.54.png](https://images.zenhubusercontent.com/61c38baf6dfd9eeb3b923d28/6f1d7c95-7bbb-4ca0-b931-be562f765449)
