### ISSUE TITLE
research ceramic for updating beneficiary information

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#963]
* decentralization plans
* ongoing operational costs w/ running own ceramic node
* report / analyze stream workflows and ACLs on streams
* how to remove/takedown/delete data - who is able to do this and what limitations or constraints might there be

**Comment by anthonymartin** [comment]
Running Ceramic in production docs: https://developers.ceramic.network/run/nodes/nodes/





> Amir J

> Actually they have conflicting statements on their docs lol --
> "Controllers are entities allowed to perform updates to a stream, by creating new signed commits. A given stream may have one controller only."
> "Controllers are entities allowed to perform updates to a stream, by creating new signed commits. A given stream may have one or more controllers."
> I'm 90% sure you can add additional controllers (edited)

**Comment by Amirjab21** [comment]
Reply from Ceramic team on Discord:

"Good catch! This used to be supported but going forward, a stream can have only one controller."

So only one controller/wallet can control a data stream.
