### ISSUE TITLE
Landing Page 2022 - popcorndao.finance (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#969]
## Description
In the reference image below, you are looking at the brand new page for the popcorndao.network site. 
Explainer Loom video: https://www.loom.com/share/a264dcae4b3846779152a183156f5066

## Specific Acceptance Criteria
- 12 column grids system (Please study the Figma file)
- use nextJS images (faster load)
- Fetch data for all TVL and vAPR for individual products
- Button hover states for "Connect" and "Submit"
- Button hover and click state for key CTA "Connect Wallet" "View"
- Layout of the page
- Submit email function should work as normal for the Newsletter sign up
- Scroll and lock to screen element for the Security header lockup 
- Popcorn should be auto-selected upon landing on the page. The popcorn icon and the Popcorn text tab take the user to the landing (Home)
- Dropdown menu should work as usual

## Resources
(Please study the Figma file carefully.)
https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=993%3A12283

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
States:
![Screen Shot 2022-07-19 at 11.40.24 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/76f92d2e-ee1a-40e0-b8d6-8085c3fbfff9)
Dropdowns:
![Screen Shot 2022-07-19 at 11.40.42 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/0b79d6dd-c860-4f4a-ad3e-10cec74103dc)
Page:
![Screen Shot 2022-07-19 at 11.40.02 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/7f1ff1b0-5a68-4a59-bc1b-6384682990e3)

**Comment by FanFanDAO** [comment]
@Ajiva-D feedback: https://www.loom.com/share/c7272f9e8477448790f96e012b8a5fc6

**Comment by FanFanDAO** [comment]
@Ajiva-D @RedVeil We need to have this dropdown and items for the top nav. It is missing right now.
![Screen Shot 2022-08-12 at 8.33.52 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/dd66eca8-9bf6-4e36-817f-412f0487835c)

**Comment by FanFanDAO** [comment]
@Ajiva-D In case I missed mentioned on the loom video. we need to address this footer in the respective width ranges:
![Screen Shot 2022-08-15 at 5.42.04 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/447ad76c-7b17-48b3-80af-3dde8e4db7c8)
![Screen Shot 2022-08-15 at 5.41.57 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/fa15eb8d-ec38-49f9-b56a-5e95084558c2)

**Comment by FanFanDAO** [comment]
@Ajiva-D did you fix anything from the loom video? I don't see any changes from https://deploy-preview-1009--sweet-caramel.netlify.app/ethereum

![Screen Shot 2022-08-16 at 3.47.14 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/abc68469-6a73-4a27-9e29-8809bb0f49de)
![Screen Shot 2022-08-16 at 3.47.09 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/77a1648e-98ba-4c05-8245-ec5bb27eca42)
![Screen Shot 2022-08-16 at 3.47.19 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8aaae9fa-416a-492f-896b-e84d95b63e86)

**Comment by Ajiva-D** [comment]
this is it @FanFanDAO https://sweet-caramel-git-new-website-design-popcorn-dao.vercel.app/

**Comment by FanFanDAO** [comment]
@Ajiva-D feedback (Please view video and images):
https://www.loom.com/share/3643e7fbb22c42d6acf35f8f32639f2c
![Screen Shot 2022-08-17 at 6.00.34 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/492602ff-4b8d-433b-b491-abe27385325b)
![Screen-Shot-2022-08-17-at-5.52.58-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/29666645-e14e-4576-aaa5-0573f0eb0dcc)

**Comment by FanFanDAO** [comment]
@Ajiva-D 
![Screen Shot 2022-08-17 at 5.44.47 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d298e278-ce03-4ebe-adbf-8de4a86e7dd5)

**Comment by FanFanDAO** [comment]
@Ajiva-D @anthonymartin Feedback:
https://www.loom.com/share/d55d23bea0cf492d9b5dcac9afc1b7ac
![Screen Shot 2022-08-18 at 12.31.00 PM.psd](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/eb76bab9-bc26-4132-a31a-d37df770d6e2)
![Screen-Shot-2022-08-18-at-12.30.38-PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/daf5f769-c059-4b51-8010-7fa638aa9f27)

@anthonymartin @RedVeil, can we group this into one Div and follow the grid instead?
![Screen Shot 2022-08-18 at 12.27.57 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/43685101-67b4-4c64-9d58-214933dd0b72)

**Comment by FanFanDAO** [comment]
@Ajiva-D Less priority on this one but get to it asap.
![screen-shot-2022-08-18-at-1.11.48-pm.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/7e0a7c72-bd24-4c78-a24d-fdee17bb1b0b)
![Screen Shot 2022-08-18 at 1.15.24 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f0e8b959-b94e-4ea8-a884-c26ce187b789)
![Screen Shot 2022-08-18 at 1.15.21 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/70755546-356a-4b09-9f7c-8e1cff68935d)
![Screen Shot 2022-08-18 at 1.15.16 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f02f79d3-63e4-4d78-9ecc-9bd1a3e33cae)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feeback:
![Screen Shot 2022-08-18 at 1.27.32 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d7c262ea-4413-4d07-b418-91ffd7eb9052)

**Comment by FanFanDAO** [comment]
@Ajiva-D feedback:
![Screen-Shot-2022-08-18-at-5.36.55-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/fc6fee27-6bbf-41f2-8b7b-d732b11b577c)

**Comment by FanFanDAO** [comment]
@Ajiva-D feedback:
We are missing the "Audited by" tag on mobile.
![Screen Shot 2022-08-19 at 10.37.34 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/56f0c29d-51a6-42b8-a272-4369bce611fc)
