### ISSUE TITLE
Update Staking Form (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#973]
## Description
We have readjusted the way we select tokens. Please look at the reference image below for details.

## Specific Acceptance Criteria
- Adjustment applies to desktop & mobile screens
- Max button outside the input field

## Resource
https://www.figma.com/file/5bmpYjaYkpoefISS9afbHc/Design-System?node-id=6502%3A4690

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Stake.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/0b48d936-fcf8-4687-b24b-0fd74a21efd5)
![Unstake.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2f5a3ef5-c015-4485-8720-686329473f4d)

**Comment by anthonymartin** [comment]
duplicated by #975
