### ISSUE TITLE
Mint & Redeem Form - Butter & 3X (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#974]
## Description
We have readjusted the way we select tokens. Please look at the reference image below for details.

## Specific Acceptance Criteria
- Adjustment applies to desktop & mobile screens
- Max button outside the input field
- Full functioning desktop token selector
- Full functioning mobile token selector

## Resource
https://www.figma.com/file/5bmpYjaYkpoefISS9afbHc/Design-System?node-id=6502%3A4690

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Mint.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/6a53feed-b69d-4d3d-bab9-b4aa117f1e02)
![Redeem.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d22d52f9-b544-455e-b299-b3b16cf7f2b2)
Desktop token selector:
![Screen Shot 2022-07-19 at 8.54.38 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/5fe751b4-47d6-4e96-8ec0-6cb240297c67)
Mobile token selector:
![Screen Shot 2022-07-19 at 8.46.57 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1f87e459-1ba4-4269-9ee0-42b6ceb35916)

**Comment by anthonymartin** [comment]
duplicates #975
