### ISSUE TITLE
[feat] min deposit size

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#977]
**Description**

We'd like to add a minimum deposit size for butter & 3x.

**Acceptance Criteria**

On butter and 3x, if a user tries to make a deposit with a value less than $100, then upon clicking the approve or mint button, then a modal should be displayed saying,

title: "Minimum Deposit"
body: "The minimum deposit amount is $100, please increase the deposit size and try again."

The transaction should not be submitted if the deposit minimum is not met.

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/977?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @K-G-J @RedVeil

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/1000

**Comment by RedVeil** [comment]
@anthonymartin is this for mint deposit only or also for redeem?

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/1170
