### ISSUE TITLE
Add Coinbase Wallet integration

### ISSUE THREAD

**Issue by mefuru** [popcorndao/sweet-caramel#980]
**Description**
Add Coinbase Wallet (a self-custody crypto wallet) integration

**Acceptance Criteria**
A working integration, tests passing

**Additional context**
[Docs](https://docs.cloud.coinbase.com/wallet-sdk/docs)

https://docs.cloud.coinbase.com/wallet-sdk/docs/web3-onboard

We have a contact at cb that can help us if needed:

Ryan Kingsley
Coinbase | Seattle, Washington
Senior Developer Partnership Associate
ryan.kingsley@coinbase.com
Discord: Ryan (Coinbase)#6131
Telegram: Ryan_Coinbase
Twitter: https://twitter.com/rkingsley11
LinkedIn: https://www.linkedin.com/in/ryankingsley1/

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/980?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @K-G-J @RedVeil

**Comment by Amirjab21** [comment]
Theres an issue with the wallet saying it's connected but not allowing any transactions for 15 seconds after connecting. I've made an issue on web3-onboard and have emailed Ryan, heres the current PR:

https://github.com/popcorndao/sweet-caramel/pull/1016

**Comment by Amirjab21** [comment]
I've now tested this on rinkeby and it all works fine.

One issue I had is that I don't think theres a way to import ERC20s into the Coinbase Wallet if Coinbase does not support that token themselves.

**Comment by FanFanDAO** [comment]
@anthonymartin 

From @Amirjab21 
"Hey, the second issue is intentional by Coinbase, they're not allowing unknown ERC20s to be imported into their wallet. I've just asked Ryan but he didn't respond to my last email so not sure if he will to this one"

To @Amirjab21, I saw two Coinbase wallet connect options, is this normal or should we have just one? (Macbook Pro, Chrome)
![Screen Shot 2022-08-15 at 1.04.44 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e9abae24-d1c8-4eb5-8239-66b2132cf702)

**Comment by Amirjab21** [comment]
@FanFanDAO 

Ryan responded to me suggesting that they're not going to support all ERC20s which makes me think he either misunderstood me or that he's referring to the coinbase.com website.

Once you send POP into your coinbase wallet, it appears and you can interact with our website and you can also send POP to others. This was all tested on Polygon.


I'm not sure why you have two coinbase wallet options, I only have 1 on the preview link on both Chrome and Brave, can you check again?

**Comment by FanFanDAO** [comment]
@Amirjab21 I do not use Brave at the moment but here is on chrome. It still persist.
https://www.loom.com/share/9acc808c877e46ed82909526e579cd3f

Can you check with Leon or Anthony if you don't know how to go about this? 

About Ryan's response, I definitely do think there is a miss communication. It is stated clearly that they support all ERC20 tokens in this link: https://help.coinbase.com/en/wallet/getting-started/what-types-of-crypto-does-wallet-support

**Comment by Amirjab21** [comment]
I can't replicate this issue or find anything about it online.

I've tested on Chrome, Brave and Safari and this issue does not appear for me. If someone is able to replicate this issue, then I'll be able to look at it.

@anthonymartin @RedVeil

**Comment by RedVeil** [comment]
@FanFanDAO @Amirjab21 I can also not replicate it. Tested it on linux and windows, chrome, firefox, edge.
I think this is fine.
