### ISSUE TITLE
Bug - Redeem panel

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#987]
![Screen Shot 2022-07-25 at 5.30.51 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/29b1035f-2dd7-46ed-b686-dbc222cee18f)

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/988

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/988

**Comment by arne-z** [comment]
![Screenshot_20220725_181638.png](https://images.zenhubusercontent.com/5c6e9b98b3d46374d6a0d6b3/038e2676-6d11-414d-b3d6-ac2a28e17cbf)
