### ISSUE TITLE
SC - Unstake and Withdraw, Vault

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#994]
Add a function that allows a user to withdraw staked vaultToken and redeem them.

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/994?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @K-G-J @RedVeil

**Comment by Amirjab21** [comment]
Did I miss something? Should I write tests? 

PR: https://github.com/popcorndao/sweet-caramel/pull/1012

**Comment by RedVeil** [comment]
@Amirjab21 We need to work on the ticket which changes staking fist before we can start here. Otherwise we cant write tests. Could you take a look at that? Id move this back to assigned.
