### ISSUE TITLE
SC - Make into ERC20 and WithdrawFor, Staking

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#995]
- [x] Make Staking.sol an ERC20.
- [x] Staking.sol should be non-transferable. (It should allow for approvals, mint and burn from msg.sender or for other user)
- [x] Allow to burn another users balance if they approved the msg.sender on withdraw and transfer the withdrawn funds to the msg.sender. 
- [x] Update rewards in modifier for the owner of burned StakingIOU if the owner != msg.sender.

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/995?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @K-G-J @RedVeil
