### ISSUE TITLE
SC - Zap,Deposit and Stake, ZeroXZapper

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#996]
Allow to depositAndStake in zapIn.
- [x] Add bool ZeroXZapper.zapIn() for `stake` to control this behavior and choose deposit or depositAndStake after the zap based on the bool.
- [x] Add bool to the call in Zapper.ts
- [x] Add a new test for ZeroXZapper.t.sol
- [x] Add a new test for ZapperModule.test.ts

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/runs/7975151235?check_suite_focus=true
