### ISSUE TITLE
Frontend - Add New Interactions

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#998]
- [x] Change the MainActionButton to "Deposit & Stake" /  "Unstake & Redeem".
- [x] Connect the new MainActionButton with the described functionality
- [x] Show added staking vAPR on SweetVault.tsx
- [x] Add approval for staking IOU for redeem (staking.approve())

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/998?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @K-G-J @RedVeil

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/1208
